// Code generated by tools/api-generate; DO NOT EDIT.

package client

import (
	"context"

	v1 "github.com/ob-labs/powercontext-go/api/v1"
)

type normalizedInvoker struct{ raw v1.Invoker }

var _ v1.Invoker = normalizedInvoker{}

func (i normalizedInvoker) AcknowledgeHandoff(ctx context.Context, request *v1.AcknowledgeHandoffRequest) (v1.AcknowledgeHandoffRes, error) {
	if err := validateOperationRequest("/v1/work/handoffs/acknowledge", request); err != nil {
		var zero v1.AcknowledgeHandoffRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/work/handoffs/acknowledge", successStatus: 200}, func(ctx context.Context) (v1.AcknowledgeHandoffRes, error) {
		return i.raw.AcknowledgeHandoff(ctx, request)
	})
}

func (i normalizedInvoker) ActivateHandoff(ctx context.Context, request *v1.ActivateHandoffRequest) (v1.ActivateHandoffRes, error) {
	if err := validateOperationRequest("/v1/handoff/activate", request); err != nil {
		var zero v1.ActivateHandoffRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff/activate", successStatus: 200}, func(ctx context.Context) (v1.ActivateHandoffRes, error) {
		return i.raw.ActivateHandoff(ctx, request)
	})
}

func (i normalizedInvoker) ApproveArtifactCandidate(ctx context.Context, request *v1.ApproveArtifactCandidateRequest) (v1.ApproveArtifactCandidateRes, error) {
	if err := validateOperationRequest("/v1/artifact-candidates/approve", request); err != nil {
		var zero v1.ApproveArtifactCandidateRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/artifact-candidates/approve", successStatus: 200}, func(ctx context.Context) (v1.ApproveArtifactCandidateRes, error) {
		return i.raw.ApproveArtifactCandidate(ctx, request)
	})
}

func (i normalizedInvoker) AttachHandoffReportWorkspace(ctx context.Context, request *v1.AttachHandoffReportWorkspaceRequest) (v1.AttachHandoffReportWorkspaceRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/workspace-bindings/attach", request); err != nil {
		var zero v1.AttachHandoffReportWorkspaceRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/workspace-bindings/attach", successStatus: 200}, func(ctx context.Context) (v1.AttachHandoffReportWorkspaceRes, error) {
		return i.raw.AttachHandoffReportWorkspace(ctx, request)
	})
}

func (i normalizedInvoker) CaptureContentSource(ctx context.Context, request *v1.CaptureContentSourceRequest) (v1.CaptureContentSourceRes, error) {
	if err := validateOperationRequest("/v1/sources/content", request); err != nil {
		var zero v1.CaptureContentSourceRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/sources/content", successStatus: 202}, func(ctx context.Context) (v1.CaptureContentSourceRes, error) {
		return i.raw.CaptureContentSource(ctx, request)
	})
}

func (i normalizedInvoker) ClearScopeBinding(ctx context.Context, request *v1.ClearScopeBindingRequest) (v1.ClearScopeBindingRes, error) {
	if err := validateOperationRequest("/v1/scope-bindings/clear", request); err != nil {
		var zero v1.ClearScopeBindingRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/scope-bindings/clear", successStatus: 200}, func(ctx context.Context) (v1.ClearScopeBindingRes, error) {
		return i.raw.ClearScopeBinding(ctx, request)
	})
}

func (i normalizedInvoker) CommitHandoff(ctx context.Context, request *v1.CommitHandoffRequest) (v1.CommitHandoffRes, error) {
	if err := validateOperationRequest("/v1/handoff/commit", request); err != nil {
		var zero v1.CommitHandoffRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff/commit", successStatus: 200}, func(ctx context.Context) (v1.CommitHandoffRes, error) {
		return i.raw.CommitHandoff(ctx, request)
	})
}

func (i normalizedInvoker) ContinueHandoff(ctx context.Context, request *v1.ContinueHandoffRequest) (v1.ContinueHandoffRes, error) {
	if err := validateOperationRequest("/v1/handoff/continue", request); err != nil {
		var zero v1.ContinueHandoffRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff/continue", successStatus: 200}, func(ctx context.Context) (v1.ContinueHandoffRes, error) {
		return i.raw.ContinueHandoff(ctx, request)
	})
}

func (i normalizedInvoker) CreateHandoffReportProject(ctx context.Context, request *v1.CreateHandoffReportProjectRequest) (v1.CreateHandoffReportProjectRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/projects/create", request); err != nil {
		var zero v1.CreateHandoffReportProjectRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/projects/create", successStatus: 201}, func(ctx context.Context) (v1.CreateHandoffReportProjectRes, error) {
		return i.raw.CreateHandoffReportProject(ctx, request)
	})
}

func (i normalizedInvoker) CreateWorkContract(ctx context.Context, request *v1.CreateWorkContractRequest) (v1.CreateWorkContractRes, error) {
	if err := validateOperationRequest("/v1/work/contracts/create", request); err != nil {
		var zero v1.CreateWorkContractRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/work/contracts/create", successStatus: 202}, func(ctx context.Context) (v1.CreateWorkContractRes, error) {
		return i.raw.CreateWorkContract(ctx, request)
	})
}

func (i normalizedInvoker) DetachHandoffReportWorkspace(ctx context.Context, request *v1.DetachHandoffReportWorkspaceRequest) (v1.DetachHandoffReportWorkspaceRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/workspace-bindings/detach", request); err != nil {
		var zero v1.DetachHandoffReportWorkspaceRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/workspace-bindings/detach", successStatus: 200}, func(ctx context.Context) (v1.DetachHandoffReportWorkspaceRes, error) {
		return i.raw.DetachHandoffReportWorkspace(ctx, request)
	})
}

func (i normalizedInvoker) FinalizeHandoff(ctx context.Context, request *v1.FinalizeHandoffRequest) (v1.FinalizeHandoffRes, error) {
	if err := validateOperationRequest("/v1/handoff/finalize", request); err != nil {
		var zero v1.FinalizeHandoffRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff/finalize", successStatus: 200}, func(ctx context.Context) (v1.FinalizeHandoffRes, error) {
		return i.raw.FinalizeHandoff(ctx, request)
	})
}

func (i normalizedInvoker) FlushMemory(ctx context.Context, request *v1.FlushMemoryRequest) (v1.FlushMemoryRes, error) {
	if err := validateOperationRequest("/v1/memory/flush", request); err != nil {
		var zero v1.FlushMemoryRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/memory/flush", successStatus: 200}, func(ctx context.Context) (v1.FlushMemoryRes, error) {
		return i.raw.FlushMemory(ctx, request)
	})
}

func (i normalizedInvoker) GenerateExperience(ctx context.Context, request *v1.GenerateExperienceRequest) (v1.GenerateExperienceRes, error) {
	if err := validateOperationRequest("/v1/experience/generate", request); err != nil {
		var zero v1.GenerateExperienceRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/experience/generate", successStatus: 200}, func(ctx context.Context) (v1.GenerateExperienceRes, error) {
		return i.raw.GenerateExperience(ctx, request)
	})
}

func (i normalizedInvoker) GenerateSkill(ctx context.Context, request *v1.GenerateSkillRequest) (v1.GenerateSkillRes, error) {
	if err := validateOperationRequest("/v1/skill/generate", request); err != nil {
		var zero v1.GenerateSkillRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/skill/generate", successStatus: 200}, func(ctx context.Context) (v1.GenerateSkillRes, error) {
		return i.raw.GenerateSkill(ctx, request)
	})
}

func (i normalizedInvoker) GetArtifactCandidate(ctx context.Context, request *v1.GetArtifactCandidateRequest) (v1.GetArtifactCandidateRes, error) {
	if err := validateOperationRequest("/v1/artifact-candidates/get", request); err != nil {
		var zero v1.GetArtifactCandidateRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/artifact-candidates/get", successStatus: 200}, func(ctx context.Context) (v1.GetArtifactCandidateRes, error) {
		return i.raw.GetArtifactCandidate(ctx, request)
	})
}

func (i normalizedInvoker) GetCapabilities(ctx context.Context) (v1.GetCapabilitiesRes, error) {
	return invokeOperation(ctx, operationDescriptor{path: "/v1/capabilities", successStatus: 200}, func(ctx context.Context) (v1.GetCapabilitiesRes, error) {
		return i.raw.GetCapabilities(ctx)
	})
}

func (i normalizedInvoker) GetExperience(ctx context.Context, request *v1.GetExperienceRequest) (v1.GetExperienceRes, error) {
	if err := validateOperationRequest("/v1/experience/get", request); err != nil {
		var zero v1.GetExperienceRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/experience/get", successStatus: 200}, func(ctx context.Context) (v1.GetExperienceRes, error) {
		return i.raw.GetExperience(ctx, request)
	})
}

func (i normalizedInvoker) GetHandoffReport(ctx context.Context, request *v1.GetHandoffReportRequest) (v1.GetHandoffReportRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/get", request); err != nil {
		var zero v1.GetHandoffReportRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/get", successStatus: 200}, func(ctx context.Context) (v1.GetHandoffReportRes, error) {
		return i.raw.GetHandoffReport(ctx, request)
	})
}

func (i normalizedInvoker) GetHandoffReportProject(ctx context.Context, request *v1.GetHandoffReportProjectRequest) (v1.GetHandoffReportProjectRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/projects/get", request); err != nil {
		var zero v1.GetHandoffReportProjectRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/projects/get", successStatus: 200}, func(ctx context.Context) (v1.GetHandoffReportProjectRes, error) {
		return i.raw.GetHandoffReportProject(ctx, request)
	})
}

func (i normalizedInvoker) GetHandoffReportWorkspace(ctx context.Context, request *v1.GetHandoffReportWorkspaceRequest) (v1.GetHandoffReportWorkspaceRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/workspace-bindings/get", request); err != nil {
		var zero v1.GetHandoffReportWorkspaceRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/workspace-bindings/get", successStatus: 200}, func(ctx context.Context) (v1.GetHandoffReportWorkspaceRes, error) {
		return i.raw.GetHandoffReportWorkspace(ctx, request)
	})
}

func (i normalizedInvoker) GetLiveness(ctx context.Context) (*v1.HealthResponseHeaders, error) {
	return invokeOperation(ctx, operationDescriptor{path: "/health/live", successStatus: 200}, func(ctx context.Context) (*v1.HealthResponseHeaders, error) {
		return i.raw.GetLiveness(ctx)
	})
}

func (i normalizedInvoker) GetMemoryEntry(ctx context.Context, request *v1.GetMemoryEntryRequest) (v1.GetMemoryEntryRes, error) {
	if err := validateOperationRequest("/v1/memory/entries/get", request); err != nil {
		var zero v1.GetMemoryEntryRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/memory/entries/get", successStatus: 200}, func(ctx context.Context) (v1.GetMemoryEntryRes, error) {
		return i.raw.GetMemoryEntry(ctx, request)
	})
}

func (i normalizedInvoker) GetReadiness(ctx context.Context) (v1.GetReadinessRes, error) {
	return invokeOperation(ctx, operationDescriptor{path: "/health/ready", successStatus: 200}, func(ctx context.Context) (v1.GetReadinessRes, error) {
		return i.raw.GetReadiness(ctx)
	})
}

func (i normalizedInvoker) GetSkill(ctx context.Context, request *v1.GetSkillRequest) (v1.GetSkillRes, error) {
	if err := validateOperationRequest("/v1/skill/get", request); err != nil {
		var zero v1.GetSkillRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/skill/get", successStatus: 200}, func(ctx context.Context) (v1.GetSkillRes, error) {
		return i.raw.GetSkill(ctx, request)
	})
}

func (i normalizedInvoker) GetStats(ctx context.Context, params v1.GetStatsParams) (v1.GetStatsRes, error) {
	if err := validateOperationRequest("/v1/stats", &params); err != nil {
		var zero v1.GetStatsRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/stats", successStatus: 200}, func(ctx context.Context) (v1.GetStatsRes, error) {
		return i.raw.GetStats(ctx, params)
	})
}

func (i normalizedInvoker) HandoffCurrentWork(ctx context.Context, request *v1.HandoffCurrentWorkRequest) (v1.HandoffCurrentWorkRes, error) {
	if err := validateOperationRequest("/v1/work/handoffs/prepare-current", request); err != nil {
		var zero v1.HandoffCurrentWorkRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/work/handoffs/prepare-current", successStatus: 200}, func(ctx context.Context) (v1.HandoffCurrentWorkRes, error) {
		return i.raw.HandoffCurrentWork(ctx, request)
	})
}

func (i normalizedInvoker) ImportExternalSkill(ctx context.Context, request *v1.ImportExternalSkillRequest) (v1.ImportExternalSkillRes, error) {
	if err := validateOperationRequest("/v1/external-skills/import", request); err != nil {
		var zero v1.ImportExternalSkillRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/external-skills/import", successStatus: 200}, func(ctx context.Context) (v1.ImportExternalSkillRes, error) {
		return i.raw.ImportExternalSkill(ctx, request)
	})
}

func (i normalizedInvoker) ListArtifactCandidates(ctx context.Context, request *v1.ListArtifactCandidatesRequest) (v1.ListArtifactCandidatesRes, error) {
	if err := validateOperationRequest("/v1/artifact-candidates/list", request); err != nil {
		var zero v1.ListArtifactCandidatesRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/artifact-candidates/list", successStatus: 200}, func(ctx context.Context) (v1.ListArtifactCandidatesRes, error) {
		return i.raw.ListArtifactCandidates(ctx, request)
	})
}

func (i normalizedInvoker) ListExternalSkills(ctx context.Context, request *v1.ListExternalSkillsRequest) (v1.ListExternalSkillsRes, error) {
	if err := validateOperationRequest("/v1/external-skills/list", request); err != nil {
		var zero v1.ListExternalSkillsRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/external-skills/list", successStatus: 200}, func(ctx context.Context) (v1.ListExternalSkillsRes, error) {
		return i.raw.ListExternalSkills(ctx, request)
	})
}

func (i normalizedInvoker) ListHandoffReportActivities(ctx context.Context, request *v1.ListHandoffReportActivitiesRequest) (v1.ListHandoffReportActivitiesRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/activities/list", request); err != nil {
		var zero v1.ListHandoffReportActivitiesRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/activities/list", successStatus: 200}, func(ctx context.Context) (v1.ListHandoffReportActivitiesRes, error) {
		return i.raw.ListHandoffReportActivities(ctx, request)
	})
}

func (i normalizedInvoker) ListHandoffReportKnownScopes(ctx context.Context, request *v1.ListHandoffReportKnownScopesRequest) (v1.ListHandoffReportKnownScopesRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/scopes/list-known", request); err != nil {
		var zero v1.ListHandoffReportKnownScopesRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/scopes/list-known", successStatus: 200}, func(ctx context.Context) (v1.ListHandoffReportKnownScopesRes, error) {
		return i.raw.ListHandoffReportKnownScopes(ctx, request)
	})
}

func (i normalizedInvoker) ListHandoffReportProjects(ctx context.Context, request *v1.ListHandoffReportProjectsRequest) (v1.ListHandoffReportProjectsRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/projects/list", request); err != nil {
		var zero v1.ListHandoffReportProjectsRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/projects/list", successStatus: 200}, func(ctx context.Context) (v1.ListHandoffReportProjectsRes, error) {
		return i.raw.ListHandoffReportProjects(ctx, request)
	})
}

func (i normalizedInvoker) ListHandoffReportWorkstreams(ctx context.Context, request *v1.ListHandoffReportWorkstreamsRequest) (v1.ListHandoffReportWorkstreamsRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/workstreams/list", request); err != nil {
		var zero v1.ListHandoffReportWorkstreamsRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/workstreams/list", successStatus: 200}, func(ctx context.Context) (v1.ListHandoffReportWorkstreamsRes, error) {
		return i.raw.ListHandoffReportWorkstreams(ctx, request)
	})
}

func (i normalizedInvoker) ListMemoryChanges(ctx context.Context, request *v1.ListMemoryChangesRequest) (v1.ListMemoryChangesRes, error) {
	if err := validateOperationRequest("/v1/memory/changes", request); err != nil {
		var zero v1.ListMemoryChangesRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/memory/changes", successStatus: 200}, func(ctx context.Context) (v1.ListMemoryChangesRes, error) {
		return i.raw.ListMemoryChanges(ctx, request)
	})
}

func (i normalizedInvoker) ListMemoryEntries(ctx context.Context, request *v1.ListMemoryEntriesRequest) (v1.ListMemoryEntriesRes, error) {
	if err := validateOperationRequest("/v1/memory/entries/list", request); err != nil {
		var zero v1.ListMemoryEntriesRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/memory/entries/list", successStatus: 200}, func(ctx context.Context) (v1.ListMemoryEntriesRes, error) {
		return i.raw.ListMemoryEntries(ctx, request)
	})
}

func (i normalizedInvoker) PrepareContext(ctx context.Context, request *v1.PrepareContextRequest) (v1.PrepareContextRes, error) {
	if err := validateOperationRequest("/v1/context/prepare", request); err != nil {
		var zero v1.PrepareContextRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/context/prepare", successStatus: 200}, func(ctx context.Context) (v1.PrepareContextRes, error) {
		return i.raw.PrepareContext(ctx, request)
	})
}

func (i normalizedInvoker) PrepareHandoff(ctx context.Context, request *v1.PrepareHandoffRequest) (v1.PrepareHandoffRes, error) {
	if err := validateOperationRequest("/v1/handoff/prepare", request); err != nil {
		var zero v1.PrepareHandoffRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff/prepare", successStatus: 200}, func(ctx context.Context) (v1.PrepareHandoffRes, error) {
		return i.raw.PrepareHandoff(ctx, request)
	})
}

func (i normalizedInvoker) ProposeExperience(ctx context.Context, request *v1.ProposeExperienceRequest) (v1.ProposeExperienceRes, error) {
	if err := validateOperationRequest("/v1/experience/propose", request); err != nil {
		var zero v1.ProposeExperienceRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/experience/propose", successStatus: 201}, func(ctx context.Context) (v1.ProposeExperienceRes, error) {
		return i.raw.ProposeExperience(ctx, request)
	})
}

func (i normalizedInvoker) ProposeSkill(ctx context.Context, request *v1.ProposeSkillRequest) (v1.ProposeSkillRes, error) {
	if err := validateOperationRequest("/v1/skill/propose", request); err != nil {
		var zero v1.ProposeSkillRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/skill/propose", successStatus: 201}, func(ctx context.Context) (v1.ProposeSkillRes, error) {
		return i.raw.ProposeSkill(ctx, request)
	})
}

func (i normalizedInvoker) PurgeHandoffReportActivities(ctx context.Context, request *v1.PurgeHandoffReportActivitiesRequest) (v1.PurgeHandoffReportActivitiesRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/activities/purge", request); err != nil {
		var zero v1.PurgeHandoffReportActivitiesRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/activities/purge", successStatus: 200}, func(ctx context.Context) (v1.PurgeHandoffReportActivitiesRes, error) {
		return i.raw.PurgeHandoffReportActivities(ctx, request)
	})
}

func (i normalizedInvoker) RecordHandoffReportActivity(ctx context.Context, request *v1.RecordHandoffReportActivityRequest) (v1.RecordHandoffReportActivityRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/activities/record", request); err != nil {
		var zero v1.RecordHandoffReportActivityRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/activities/record", successStatus: 201}, func(ctx context.Context) (v1.RecordHandoffReportActivityRes, error) {
		return i.raw.RecordHandoffReportActivity(ctx, request)
	})
}

func (i normalizedInvoker) RecordTaskOutcome(ctx context.Context, request *v1.RecordTaskOutcomeRequest) (v1.RecordTaskOutcomeRes, error) {
	if err := validateOperationRequest("/v1/work/outcomes/record", request); err != nil {
		var zero v1.RecordTaskOutcomeRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/work/outcomes/record", successStatus: 202}, func(ctx context.Context) (v1.RecordTaskOutcomeRes, error) {
		return i.raw.RecordTaskOutcome(ctx, request)
	})
}

func (i normalizedInvoker) RegisterHandoffReportWorkstream(ctx context.Context, request *v1.RegisterHandoffReportWorkstreamRequest) (v1.RegisterHandoffReportWorkstreamRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/workstreams/register", request); err != nil {
		var zero v1.RegisterHandoffReportWorkstreamRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/workstreams/register", successStatus: 201}, func(ctx context.Context) (v1.RegisterHandoffReportWorkstreamRes, error) {
		return i.raw.RegisterHandoffReportWorkstream(ctx, request)
	})
}

func (i normalizedInvoker) RejectArtifactCandidate(ctx context.Context, request *v1.RejectArtifactCandidateRequest) (v1.RejectArtifactCandidateRes, error) {
	if err := validateOperationRequest("/v1/artifact-candidates/reject", request); err != nil {
		var zero v1.RejectArtifactCandidateRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/artifact-candidates/reject", successStatus: 200}, func(ctx context.Context) (v1.RejectArtifactCandidateRes, error) {
		return i.raw.RejectArtifactCandidate(ctx, request)
	})
}

func (i normalizedInvoker) RememberMemory(ctx context.Context, request *v1.RememberMemoryRequest) (v1.RememberMemoryRes, error) {
	if err := validateOperationRequest("/v1/memory/remember", request); err != nil {
		var zero v1.RememberMemoryRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/memory/remember", successStatus: 200}, func(ctx context.Context) (v1.RememberMemoryRes, error) {
		return i.raw.RememberMemory(ctx, request)
	})
}

func (i normalizedInvoker) ResolveExternalSkill(ctx context.Context, request *v1.ResolveExternalSkillRequest) (v1.ResolveExternalSkillRes, error) {
	if err := validateOperationRequest("/v1/external-skills/resolve", request); err != nil {
		var zero v1.ResolveExternalSkillRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/external-skills/resolve", successStatus: 200}, func(ctx context.Context) (v1.ResolveExternalSkillRes, error) {
		return i.raw.ResolveExternalSkill(ctx, request)
	})
}

func (i normalizedInvoker) ResolveScopeBinding(ctx context.Context, request *v1.ResolveScopeBindingRequest) (v1.ResolveScopeBindingRes, error) {
	if err := validateOperationRequest("/v1/scope-bindings/resolve", request); err != nil {
		var zero v1.ResolveScopeBindingRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/scope-bindings/resolve", successStatus: 200}, func(ctx context.Context) (v1.ResolveScopeBindingRes, error) {
		return i.raw.ResolveScopeBinding(ctx, request)
	})
}

func (i normalizedInvoker) RetireMemoryEntry(ctx context.Context, request *v1.RetireMemoryEntryRequest) (v1.RetireMemoryEntryRes, error) {
	if err := validateOperationRequest("/v1/memory/entries/retire", request); err != nil {
		var zero v1.RetireMemoryEntryRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/memory/entries/retire", successStatus: 200}, func(ctx context.Context) (v1.RetireMemoryEntryRes, error) {
		return i.raw.RetireMemoryEntry(ctx, request)
	})
}

func (i normalizedInvoker) ReviseArtifactCandidate(ctx context.Context, request *v1.ReviseArtifactCandidateRequest) (v1.ReviseArtifactCandidateRes, error) {
	if err := validateOperationRequest("/v1/artifact-candidates/revise", request); err != nil {
		var zero v1.ReviseArtifactCandidateRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/artifact-candidates/revise", successStatus: 200}, func(ctx context.Context) (v1.ReviseArtifactCandidateRes, error) {
		return i.raw.ReviseArtifactCandidate(ctx, request)
	})
}

func (i normalizedInvoker) ReviseMemoryEntry(ctx context.Context, request *v1.ReviseMemoryEntryRequest) (v1.ReviseMemoryEntryRes, error) {
	if err := validateOperationRequest("/v1/memory/entries/revise", request); err != nil {
		var zero v1.ReviseMemoryEntryRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/memory/entries/revise", successStatus: 200}, func(ctx context.Context) (v1.ReviseMemoryEntryRes, error) {
		return i.raw.ReviseMemoryEntry(ctx, request)
	})
}

func (i normalizedInvoker) ScanExternalSkills(ctx context.Context, request *v1.ScanExternalSkillsRequest) (v1.ScanExternalSkillsRes, error) {
	if err := validateOperationRequest("/v1/external-skills/scan", request); err != nil {
		var zero v1.ScanExternalSkillsRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/external-skills/scan", successStatus: 200}, func(ctx context.Context) (v1.ScanExternalSkillsRes, error) {
		return i.raw.ScanExternalSkills(ctx, request)
	})
}

func (i normalizedInvoker) SearchMemory(ctx context.Context, request *v1.SearchMemoryRequest) (v1.SearchMemoryRes, error) {
	if err := validateOperationRequest("/v1/memory/search", request); err != nil {
		var zero v1.SearchMemoryRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/memory/search", successStatus: 200}, func(ctx context.Context) (v1.SearchMemoryRes, error) {
		return i.raw.SearchMemory(ctx, request)
	})
}

func (i normalizedInvoker) SetScopeBinding(ctx context.Context, request *v1.ScopeBinding) (v1.SetScopeBindingRes, error) {
	if err := validateOperationRequest("/v1/scope-bindings", request); err != nil {
		var zero v1.SetScopeBindingRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/scope-bindings", successStatus: 200}, func(ctx context.Context) (v1.SetScopeBindingRes, error) {
		return i.raw.SetScopeBinding(ctx, request)
	})
}

func (i normalizedInvoker) UpdateHandoffReportProject(ctx context.Context, request *v1.UpdateHandoffReportProjectRequest) (v1.UpdateHandoffReportProjectRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/projects/update", request); err != nil {
		var zero v1.UpdateHandoffReportProjectRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/projects/update", successStatus: 200}, func(ctx context.Context) (v1.UpdateHandoffReportProjectRes, error) {
		return i.raw.UpdateHandoffReportProject(ctx, request)
	})
}

func (i normalizedInvoker) UpdateHandoffReportWorkstream(ctx context.Context, request *v1.UpdateHandoffReportWorkstreamRequest) (v1.UpdateHandoffReportWorkstreamRes, error) {
	if err := validateOperationRequest("/v1/handoff-reports/workstreams/update", request); err != nil {
		var zero v1.UpdateHandoffReportWorkstreamRes
		return zero, err
	}
	return invokeOperation(ctx, operationDescriptor{path: "/v1/handoff-reports/workstreams/update", successStatus: 200}, func(ctx context.Context) (v1.UpdateHandoffReportWorkstreamRes, error) {
		return i.raw.UpdateHandoffReportWorkstream(ctx, request)
	})
}
