// Code generated by ogen, DO NOT EDIT.

package remoteskills

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// ConflictHeaders wraps ErrorResponse with response headers.
type ConflictHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *ConflictHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *ConflictHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *ConflictHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *ConflictHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*ConflictHeaders) createRemoteSkillTargetRes() {}
func (*ConflictHeaders) enrollRemoteSkillTargetRes() {}
func (*ConflictHeaders) renameRemoteSkillTargetRes() {}
func (*ConflictHeaders) revokeRemoteSkillTargetRes() {}

// Ref: #/components/schemas/CreateRemoteSkillTargetRequest
type CreateRemoteSkillTargetRequest struct {
	AgentKind   RemoteAgentKind `json:"agent_kind"`
	DisplayName string          `json:"display_name"`
	ScopeID     string          `json:"scope_id"`
}

// GetAgentKind returns the value of AgentKind.
func (s *CreateRemoteSkillTargetRequest) GetAgentKind() RemoteAgentKind {
	return s.AgentKind
}

// GetDisplayName returns the value of DisplayName.
func (s *CreateRemoteSkillTargetRequest) GetDisplayName() string {
	return s.DisplayName
}

// GetScopeID returns the value of ScopeID.
func (s *CreateRemoteSkillTargetRequest) GetScopeID() string {
	return s.ScopeID
}

// SetAgentKind sets the value of AgentKind.
func (s *CreateRemoteSkillTargetRequest) SetAgentKind(val RemoteAgentKind) {
	s.AgentKind = val
}

// SetDisplayName sets the value of DisplayName.
func (s *CreateRemoteSkillTargetRequest) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetScopeID sets the value of ScopeID.
func (s *CreateRemoteSkillTargetRequest) SetScopeID(val string) {
	s.ScopeID = val
}

// Ref: #/components/schemas/EnrollRemoteSkillTargetRequest
type EnrollRemoteSkillTargetRequest struct {
	EnrollmentCode         string       `json:"enrollment_code"`
	EnvironmentFingerprint OptNilString `json:"environment_fingerprint"`
	InstallationID         string       `json:"installation_id"`
	MachineHostname        OptNilString `json:"machine_hostname"`
	ReceiverVersion        string       `json:"receiver_version"`
	WorkspaceName          OptNilString `json:"workspace_name"`
}

// GetEnrollmentCode returns the value of EnrollmentCode.
func (s *EnrollRemoteSkillTargetRequest) GetEnrollmentCode() string {
	return s.EnrollmentCode
}

// GetEnvironmentFingerprint returns the value of EnvironmentFingerprint.
func (s *EnrollRemoteSkillTargetRequest) GetEnvironmentFingerprint() OptNilString {
	return s.EnvironmentFingerprint
}

// GetInstallationID returns the value of InstallationID.
func (s *EnrollRemoteSkillTargetRequest) GetInstallationID() string {
	return s.InstallationID
}

// GetMachineHostname returns the value of MachineHostname.
func (s *EnrollRemoteSkillTargetRequest) GetMachineHostname() OptNilString {
	return s.MachineHostname
}

// GetReceiverVersion returns the value of ReceiverVersion.
func (s *EnrollRemoteSkillTargetRequest) GetReceiverVersion() string {
	return s.ReceiverVersion
}

// GetWorkspaceName returns the value of WorkspaceName.
func (s *EnrollRemoteSkillTargetRequest) GetWorkspaceName() OptNilString {
	return s.WorkspaceName
}

// SetEnrollmentCode sets the value of EnrollmentCode.
func (s *EnrollRemoteSkillTargetRequest) SetEnrollmentCode(val string) {
	s.EnrollmentCode = val
}

// SetEnvironmentFingerprint sets the value of EnvironmentFingerprint.
func (s *EnrollRemoteSkillTargetRequest) SetEnvironmentFingerprint(val OptNilString) {
	s.EnvironmentFingerprint = val
}

// SetInstallationID sets the value of InstallationID.
func (s *EnrollRemoteSkillTargetRequest) SetInstallationID(val string) {
	s.InstallationID = val
}

// SetMachineHostname sets the value of MachineHostname.
func (s *EnrollRemoteSkillTargetRequest) SetMachineHostname(val OptNilString) {
	s.MachineHostname = val
}

// SetReceiverVersion sets the value of ReceiverVersion.
func (s *EnrollRemoteSkillTargetRequest) SetReceiverVersion(val string) {
	s.ReceiverVersion = val
}

// SetWorkspaceName sets the value of WorkspaceName.
func (s *EnrollRemoteSkillTargetRequest) SetWorkspaceName(val OptNilString) {
	s.WorkspaceName = val
}

// Ref: #/components/schemas/ErrorDetail
type ErrorDetail struct {
	Code    string                `json:"code"`
	Details NilErrorDetailDetails `json:"details"`
	Message string                `json:"message"`
}

// GetCode returns the value of Code.
func (s *ErrorDetail) GetCode() string {
	return s.Code
}

// GetDetails returns the value of Details.
func (s *ErrorDetail) GetDetails() NilErrorDetailDetails {
	return s.Details
}

// GetMessage returns the value of Message.
func (s *ErrorDetail) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ErrorDetail) SetCode(val string) {
	s.Code = val
}

// SetDetails sets the value of Details.
func (s *ErrorDetail) SetDetails(val NilErrorDetailDetails) {
	s.Details = val
}

// SetMessage sets the value of Message.
func (s *ErrorDetail) SetMessage(val string) {
	s.Message = val
}

type ErrorDetailDetails map[string]jx.Raw

func (s *ErrorDetailDetails) init() ErrorDetailDetails {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() ErrorDetail {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val ErrorDetail) {
	s.Error = val
}

// InternalErrorHeaders wraps ErrorResponse with response headers.
type InternalErrorHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *InternalErrorHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *InternalErrorHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *InternalErrorHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *InternalErrorHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*InternalErrorHeaders) createRemoteSkillTargetRes() {}
func (*InternalErrorHeaders) enrollRemoteSkillTargetRes() {}
func (*InternalErrorHeaders) listRemoteSkillTargetsRes()  {}
func (*InternalErrorHeaders) renameRemoteSkillTargetRes() {}
func (*InternalErrorHeaders) revokeRemoteSkillTargetRes() {}

// InvalidRequestHeaders wraps ErrorResponse with response headers.
type InvalidRequestHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *InvalidRequestHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *InvalidRequestHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *InvalidRequestHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *InvalidRequestHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*InvalidRequestHeaders) createRemoteSkillTargetRes() {}
func (*InvalidRequestHeaders) enrollRemoteSkillTargetRes() {}
func (*InvalidRequestHeaders) listRemoteSkillTargetsRes()  {}
func (*InvalidRequestHeaders) renameRemoteSkillTargetRes() {}
func (*InvalidRequestHeaders) revokeRemoteSkillTargetRes() {}

// Ref: #/components/schemas/ListRemoteSkillTargetsRequest
type ListRemoteSkillTargetsRequest struct {
	Limit    OptInt       `json:"limit"`
	ScopeID  string       `json:"scope_id"`
	TargetID OptNilString `json:"target_id"`
}

// GetLimit returns the value of Limit.
func (s *ListRemoteSkillTargetsRequest) GetLimit() OptInt {
	return s.Limit
}

// GetScopeID returns the value of ScopeID.
func (s *ListRemoteSkillTargetsRequest) GetScopeID() string {
	return s.ScopeID
}

// GetTargetID returns the value of TargetID.
func (s *ListRemoteSkillTargetsRequest) GetTargetID() OptNilString {
	return s.TargetID
}

// SetLimit sets the value of Limit.
func (s *ListRemoteSkillTargetsRequest) SetLimit(val OptInt) {
	s.Limit = val
}

// SetScopeID sets the value of ScopeID.
func (s *ListRemoteSkillTargetsRequest) SetScopeID(val string) {
	s.ScopeID = val
}

// SetTargetID sets the value of TargetID.
func (s *ListRemoteSkillTargetsRequest) SetTargetID(val OptNilString) {
	s.TargetID = val
}

// Ref: #/components/schemas/ListRemoteSkillTargetsResponse
type ListRemoteSkillTargetsResponse struct {
	Targets []RemoteSkillTargetStatus `json:"targets"`
}

// GetTargets returns the value of Targets.
func (s *ListRemoteSkillTargetsResponse) GetTargets() []RemoteSkillTargetStatus {
	return s.Targets
}

// SetTargets sets the value of Targets.
func (s *ListRemoteSkillTargetsResponse) SetTargets(val []RemoteSkillTargetStatus) {
	s.Targets = val
}

func (*ListRemoteSkillTargetsResponse) listRemoteSkillTargetsRes() {}

// NewNilDateTime returns new NilDateTime with value set to v.
func NewNilDateTime(v time.Time) NilDateTime {
	return NilDateTime{
		Value: v,
	}
}

// NilDateTime is nullable time.Time.
type NilDateTime struct {
	Value time.Time
	Null  bool
}

// SetTo sets value to v.
func (o *NilDateTime) SetTo(v time.Time) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilDateTime) SetToNull() {
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilErrorDetailDetails returns new NilErrorDetailDetails with value set to v.
func NewNilErrorDetailDetails(v ErrorDetailDetails) NilErrorDetailDetails {
	return NilErrorDetailDetails{
		Value: v,
	}
}

// NilErrorDetailDetails is nullable ErrorDetailDetails.
type NilErrorDetailDetails struct {
	Value ErrorDetailDetails
	Null  bool
}

// SetTo sets value to v.
func (o *NilErrorDetailDetails) SetTo(v ErrorDetailDetails) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilErrorDetailDetails) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilErrorDetailDetails) SetToNull() {
	o.Null = true
	var v ErrorDetailDetails
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilErrorDetailDetails) Get() (v ErrorDetailDetails, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilErrorDetailDetails) Or(d ErrorDetailDetails) ErrorDetailDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilInt returns new NilInt with value set to v.
func NewNilInt(v int) NilInt {
	return NilInt{
		Value: v,
	}
}

// NilInt is nullable int.
type NilInt struct {
	Value int
	Null  bool
}

// SetTo sets value to v.
func (o *NilInt) SetTo(v int) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilInt) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilInt) SetToNull() {
	o.Null = true
	var v int
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilInt) Get() (v int, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NotFoundHeaders wraps ErrorResponse with response headers.
type NotFoundHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *NotFoundHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *NotFoundHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *NotFoundHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *NotFoundHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*NotFoundHeaders) renameRemoteSkillTargetRes() {}
func (*NotFoundHeaders) revokeRemoteSkillTargetRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/RemoteAgentKind
type RemoteAgentKind string

const (
	RemoteAgentKindCodex     RemoteAgentKind = "codex"
	RemoteAgentKindWorkbuddy RemoteAgentKind = "workbuddy"
)

// AllValues returns all RemoteAgentKind values.
func (RemoteAgentKind) AllValues() []RemoteAgentKind {
	return []RemoteAgentKind{
		RemoteAgentKindCodex,
		RemoteAgentKindWorkbuddy,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RemoteAgentKind) MarshalText() ([]byte, error) {
	switch s {
	case RemoteAgentKindCodex:
		return []byte(s), nil
	case RemoteAgentKindWorkbuddy:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RemoteAgentKind) UnmarshalText(data []byte) error {
	switch RemoteAgentKind(data) {
	case RemoteAgentKindCodex:
		*s = RemoteAgentKindCodex
		return nil
	case RemoteAgentKindWorkbuddy:
		*s = RemoteAgentKindWorkbuddy
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/RemoteSkillDesiredState
type RemoteSkillDesiredState string

const (
	RemoteSkillDesiredStatePublished   RemoteSkillDesiredState = "published"
	RemoteSkillDesiredStateUnpublished RemoteSkillDesiredState = "unpublished"
)

// AllValues returns all RemoteSkillDesiredState values.
func (RemoteSkillDesiredState) AllValues() []RemoteSkillDesiredState {
	return []RemoteSkillDesiredState{
		RemoteSkillDesiredStatePublished,
		RemoteSkillDesiredStateUnpublished,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RemoteSkillDesiredState) MarshalText() ([]byte, error) {
	switch s {
	case RemoteSkillDesiredStatePublished:
		return []byte(s), nil
	case RemoteSkillDesiredStateUnpublished:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RemoteSkillDesiredState) UnmarshalText(data []byte) error {
	switch RemoteSkillDesiredState(data) {
	case RemoteSkillDesiredStatePublished:
		*s = RemoteSkillDesiredStatePublished
		return nil
	case RemoteSkillDesiredStateUnpublished:
		*s = RemoteSkillDesiredStateUnpublished
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/RemoteSkillPublication
type RemoteSkillPublication struct {
	ArtifactID         string                      `json:"artifact_id"`
	DesiredRevision    int                         `json:"desired_revision"`
	DesiredState       RemoteSkillDesiredState     `json:"desired_state"`
	DesiredTreeDigest  string                      `json:"desired_tree_digest"`
	Generation         int                         `json:"generation"`
	LastErrorCode      NilString                   `json:"last_error_code"`
	ObservedAt         NilDateTime                 `json:"observed_at"`
	ObservedGeneration NilInt                      `json:"observed_generation"`
	ObservedRevision   NilInt                      `json:"observed_revision"`
	ObservedTreeDigest NilString                   `json:"observed_tree_digest"`
	ScopeID            string                      `json:"scope_id"`
	State              RemoteSkillPublicationState `json:"state"`
	TargetID           string                      `json:"target_id"`
}

// GetArtifactID returns the value of ArtifactID.
func (s *RemoteSkillPublication) GetArtifactID() string {
	return s.ArtifactID
}

// GetDesiredRevision returns the value of DesiredRevision.
func (s *RemoteSkillPublication) GetDesiredRevision() int {
	return s.DesiredRevision
}

// GetDesiredState returns the value of DesiredState.
func (s *RemoteSkillPublication) GetDesiredState() RemoteSkillDesiredState {
	return s.DesiredState
}

// GetDesiredTreeDigest returns the value of DesiredTreeDigest.
func (s *RemoteSkillPublication) GetDesiredTreeDigest() string {
	return s.DesiredTreeDigest
}

// GetGeneration returns the value of Generation.
func (s *RemoteSkillPublication) GetGeneration() int {
	return s.Generation
}

// GetLastErrorCode returns the value of LastErrorCode.
func (s *RemoteSkillPublication) GetLastErrorCode() NilString {
	return s.LastErrorCode
}

// GetObservedAt returns the value of ObservedAt.
func (s *RemoteSkillPublication) GetObservedAt() NilDateTime {
	return s.ObservedAt
}

// GetObservedGeneration returns the value of ObservedGeneration.
func (s *RemoteSkillPublication) GetObservedGeneration() NilInt {
	return s.ObservedGeneration
}

// GetObservedRevision returns the value of ObservedRevision.
func (s *RemoteSkillPublication) GetObservedRevision() NilInt {
	return s.ObservedRevision
}

// GetObservedTreeDigest returns the value of ObservedTreeDigest.
func (s *RemoteSkillPublication) GetObservedTreeDigest() NilString {
	return s.ObservedTreeDigest
}

// GetScopeID returns the value of ScopeID.
func (s *RemoteSkillPublication) GetScopeID() string {
	return s.ScopeID
}

// GetState returns the value of State.
func (s *RemoteSkillPublication) GetState() RemoteSkillPublicationState {
	return s.State
}

// GetTargetID returns the value of TargetID.
func (s *RemoteSkillPublication) GetTargetID() string {
	return s.TargetID
}

// SetArtifactID sets the value of ArtifactID.
func (s *RemoteSkillPublication) SetArtifactID(val string) {
	s.ArtifactID = val
}

// SetDesiredRevision sets the value of DesiredRevision.
func (s *RemoteSkillPublication) SetDesiredRevision(val int) {
	s.DesiredRevision = val
}

// SetDesiredState sets the value of DesiredState.
func (s *RemoteSkillPublication) SetDesiredState(val RemoteSkillDesiredState) {
	s.DesiredState = val
}

// SetDesiredTreeDigest sets the value of DesiredTreeDigest.
func (s *RemoteSkillPublication) SetDesiredTreeDigest(val string) {
	s.DesiredTreeDigest = val
}

// SetGeneration sets the value of Generation.
func (s *RemoteSkillPublication) SetGeneration(val int) {
	s.Generation = val
}

// SetLastErrorCode sets the value of LastErrorCode.
func (s *RemoteSkillPublication) SetLastErrorCode(val NilString) {
	s.LastErrorCode = val
}

// SetObservedAt sets the value of ObservedAt.
func (s *RemoteSkillPublication) SetObservedAt(val NilDateTime) {
	s.ObservedAt = val
}

// SetObservedGeneration sets the value of ObservedGeneration.
func (s *RemoteSkillPublication) SetObservedGeneration(val NilInt) {
	s.ObservedGeneration = val
}

// SetObservedRevision sets the value of ObservedRevision.
func (s *RemoteSkillPublication) SetObservedRevision(val NilInt) {
	s.ObservedRevision = val
}

// SetObservedTreeDigest sets the value of ObservedTreeDigest.
func (s *RemoteSkillPublication) SetObservedTreeDigest(val NilString) {
	s.ObservedTreeDigest = val
}

// SetScopeID sets the value of ScopeID.
func (s *RemoteSkillPublication) SetScopeID(val string) {
	s.ScopeID = val
}

// SetState sets the value of State.
func (s *RemoteSkillPublication) SetState(val RemoteSkillPublicationState) {
	s.State = val
}

// SetTargetID sets the value of TargetID.
func (s *RemoteSkillPublication) SetTargetID(val string) {
	s.TargetID = val
}

// Ref: #/components/schemas/RemoteSkillPublicationState
type RemoteSkillPublicationState string

const (
	RemoteSkillPublicationStateUnpublished     RemoteSkillPublicationState = "unpublished"
	RemoteSkillPublicationStatePending         RemoteSkillPublicationState = "pending"
	RemoteSkillPublicationStateCurrent         RemoteSkillPublicationState = "current"
	RemoteSkillPublicationStateUpdateAvailable RemoteSkillPublicationState = "update_available"
	RemoteSkillPublicationStateDeliveryFailed  RemoteSkillPublicationState = "delivery_failed"
	RemoteSkillPublicationStateConflict        RemoteSkillPublicationState = "conflict"
	RemoteSkillPublicationStateDrifted         RemoteSkillPublicationState = "drifted"
	RemoteSkillPublicationStateIncompatible    RemoteSkillPublicationState = "incompatible"
)

// AllValues returns all RemoteSkillPublicationState values.
func (RemoteSkillPublicationState) AllValues() []RemoteSkillPublicationState {
	return []RemoteSkillPublicationState{
		RemoteSkillPublicationStateUnpublished,
		RemoteSkillPublicationStatePending,
		RemoteSkillPublicationStateCurrent,
		RemoteSkillPublicationStateUpdateAvailable,
		RemoteSkillPublicationStateDeliveryFailed,
		RemoteSkillPublicationStateConflict,
		RemoteSkillPublicationStateDrifted,
		RemoteSkillPublicationStateIncompatible,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RemoteSkillPublicationState) MarshalText() ([]byte, error) {
	switch s {
	case RemoteSkillPublicationStateUnpublished:
		return []byte(s), nil
	case RemoteSkillPublicationStatePending:
		return []byte(s), nil
	case RemoteSkillPublicationStateCurrent:
		return []byte(s), nil
	case RemoteSkillPublicationStateUpdateAvailable:
		return []byte(s), nil
	case RemoteSkillPublicationStateDeliveryFailed:
		return []byte(s), nil
	case RemoteSkillPublicationStateConflict:
		return []byte(s), nil
	case RemoteSkillPublicationStateDrifted:
		return []byte(s), nil
	case RemoteSkillPublicationStateIncompatible:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RemoteSkillPublicationState) UnmarshalText(data []byte) error {
	switch RemoteSkillPublicationState(data) {
	case RemoteSkillPublicationStateUnpublished:
		*s = RemoteSkillPublicationStateUnpublished
		return nil
	case RemoteSkillPublicationStatePending:
		*s = RemoteSkillPublicationStatePending
		return nil
	case RemoteSkillPublicationStateCurrent:
		*s = RemoteSkillPublicationStateCurrent
		return nil
	case RemoteSkillPublicationStateUpdateAvailable:
		*s = RemoteSkillPublicationStateUpdateAvailable
		return nil
	case RemoteSkillPublicationStateDeliveryFailed:
		*s = RemoteSkillPublicationStateDeliveryFailed
		return nil
	case RemoteSkillPublicationStateConflict:
		*s = RemoteSkillPublicationStateConflict
		return nil
	case RemoteSkillPublicationStateDrifted:
		*s = RemoteSkillPublicationStateDrifted
		return nil
	case RemoteSkillPublicationStateIncompatible:
		*s = RemoteSkillPublicationStateIncompatible
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/RemoteSkillTarget
type RemoteSkillTarget struct {
	AgentKind              RemoteAgentKind                    `json:"agent_kind"`
	DeliveryMode           RemoteSkillTargetDeliveryMode      `json:"delivery_mode"`
	DisplayName            string                             `json:"display_name"`
	EnvironmentFingerprint NilString                          `json:"environment_fingerprint"`
	Generation             int                                `json:"generation"`
	InstallationID         NilString                          `json:"installation_id"`
	InstallationScope      RemoteSkillTargetInstallationScope `json:"installation_scope"`
	LastSeenAt             NilDateTime                        `json:"last_seen_at"`
	MachineHostname        NilString                          `json:"machine_hostname"`
	ReceiverVersion        NilString                          `json:"receiver_version"`
	ScopeID                string                             `json:"scope_id"`
	State                  RemoteSkillTargetState             `json:"state"`
	TargetID               string                             `json:"target_id"`
	WorkspaceName          NilString                          `json:"workspace_name"`
}

// GetAgentKind returns the value of AgentKind.
func (s *RemoteSkillTarget) GetAgentKind() RemoteAgentKind {
	return s.AgentKind
}

// GetDeliveryMode returns the value of DeliveryMode.
func (s *RemoteSkillTarget) GetDeliveryMode() RemoteSkillTargetDeliveryMode {
	return s.DeliveryMode
}

// GetDisplayName returns the value of DisplayName.
func (s *RemoteSkillTarget) GetDisplayName() string {
	return s.DisplayName
}

// GetEnvironmentFingerprint returns the value of EnvironmentFingerprint.
func (s *RemoteSkillTarget) GetEnvironmentFingerprint() NilString {
	return s.EnvironmentFingerprint
}

// GetGeneration returns the value of Generation.
func (s *RemoteSkillTarget) GetGeneration() int {
	return s.Generation
}

// GetInstallationID returns the value of InstallationID.
func (s *RemoteSkillTarget) GetInstallationID() NilString {
	return s.InstallationID
}

// GetInstallationScope returns the value of InstallationScope.
func (s *RemoteSkillTarget) GetInstallationScope() RemoteSkillTargetInstallationScope {
	return s.InstallationScope
}

// GetLastSeenAt returns the value of LastSeenAt.
func (s *RemoteSkillTarget) GetLastSeenAt() NilDateTime {
	return s.LastSeenAt
}

// GetMachineHostname returns the value of MachineHostname.
func (s *RemoteSkillTarget) GetMachineHostname() NilString {
	return s.MachineHostname
}

// GetReceiverVersion returns the value of ReceiverVersion.
func (s *RemoteSkillTarget) GetReceiverVersion() NilString {
	return s.ReceiverVersion
}

// GetScopeID returns the value of ScopeID.
func (s *RemoteSkillTarget) GetScopeID() string {
	return s.ScopeID
}

// GetState returns the value of State.
func (s *RemoteSkillTarget) GetState() RemoteSkillTargetState {
	return s.State
}

// GetTargetID returns the value of TargetID.
func (s *RemoteSkillTarget) GetTargetID() string {
	return s.TargetID
}

// GetWorkspaceName returns the value of WorkspaceName.
func (s *RemoteSkillTarget) GetWorkspaceName() NilString {
	return s.WorkspaceName
}

// SetAgentKind sets the value of AgentKind.
func (s *RemoteSkillTarget) SetAgentKind(val RemoteAgentKind) {
	s.AgentKind = val
}

// SetDeliveryMode sets the value of DeliveryMode.
func (s *RemoteSkillTarget) SetDeliveryMode(val RemoteSkillTargetDeliveryMode) {
	s.DeliveryMode = val
}

// SetDisplayName sets the value of DisplayName.
func (s *RemoteSkillTarget) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetEnvironmentFingerprint sets the value of EnvironmentFingerprint.
func (s *RemoteSkillTarget) SetEnvironmentFingerprint(val NilString) {
	s.EnvironmentFingerprint = val
}

// SetGeneration sets the value of Generation.
func (s *RemoteSkillTarget) SetGeneration(val int) {
	s.Generation = val
}

// SetInstallationID sets the value of InstallationID.
func (s *RemoteSkillTarget) SetInstallationID(val NilString) {
	s.InstallationID = val
}

// SetInstallationScope sets the value of InstallationScope.
func (s *RemoteSkillTarget) SetInstallationScope(val RemoteSkillTargetInstallationScope) {
	s.InstallationScope = val
}

// SetLastSeenAt sets the value of LastSeenAt.
func (s *RemoteSkillTarget) SetLastSeenAt(val NilDateTime) {
	s.LastSeenAt = val
}

// SetMachineHostname sets the value of MachineHostname.
func (s *RemoteSkillTarget) SetMachineHostname(val NilString) {
	s.MachineHostname = val
}

// SetReceiverVersion sets the value of ReceiverVersion.
func (s *RemoteSkillTarget) SetReceiverVersion(val NilString) {
	s.ReceiverVersion = val
}

// SetScopeID sets the value of ScopeID.
func (s *RemoteSkillTarget) SetScopeID(val string) {
	s.ScopeID = val
}

// SetState sets the value of State.
func (s *RemoteSkillTarget) SetState(val RemoteSkillTargetState) {
	s.State = val
}

// SetTargetID sets the value of TargetID.
func (s *RemoteSkillTarget) SetTargetID(val string) {
	s.TargetID = val
}

// SetWorkspaceName sets the value of WorkspaceName.
func (s *RemoteSkillTarget) SetWorkspaceName(val NilString) {
	s.WorkspaceName = val
}

func (*RemoteSkillTarget) renameRemoteSkillTargetRes() {}
func (*RemoteSkillTarget) revokeRemoteSkillTargetRes() {}

// Ref: #/components/schemas/RemoteSkillTargetCredential
type RemoteSkillTargetCredential struct {
	AgentKind  RemoteAgentKind `json:"agent_kind"`
	Credential string          `json:"credential"`
	ScopeID    string          `json:"scope_id"`
	TargetID   string          `json:"target_id"`
}

// GetAgentKind returns the value of AgentKind.
func (s *RemoteSkillTargetCredential) GetAgentKind() RemoteAgentKind {
	return s.AgentKind
}

// GetCredential returns the value of Credential.
func (s *RemoteSkillTargetCredential) GetCredential() string {
	return s.Credential
}

// GetScopeID returns the value of ScopeID.
func (s *RemoteSkillTargetCredential) GetScopeID() string {
	return s.ScopeID
}

// GetTargetID returns the value of TargetID.
func (s *RemoteSkillTargetCredential) GetTargetID() string {
	return s.TargetID
}

// SetAgentKind sets the value of AgentKind.
func (s *RemoteSkillTargetCredential) SetAgentKind(val RemoteAgentKind) {
	s.AgentKind = val
}

// SetCredential sets the value of Credential.
func (s *RemoteSkillTargetCredential) SetCredential(val string) {
	s.Credential = val
}

// SetScopeID sets the value of ScopeID.
func (s *RemoteSkillTargetCredential) SetScopeID(val string) {
	s.ScopeID = val
}

// SetTargetID sets the value of TargetID.
func (s *RemoteSkillTargetCredential) SetTargetID(val string) {
	s.TargetID = val
}

func (*RemoteSkillTargetCredential) enrollRemoteSkillTargetRes() {}

type RemoteSkillTargetDeliveryMode string

const (
	RemoteSkillTargetDeliveryModeAgentPull RemoteSkillTargetDeliveryMode = "agent_pull"
)

// AllValues returns all RemoteSkillTargetDeliveryMode values.
func (RemoteSkillTargetDeliveryMode) AllValues() []RemoteSkillTargetDeliveryMode {
	return []RemoteSkillTargetDeliveryMode{
		RemoteSkillTargetDeliveryModeAgentPull,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RemoteSkillTargetDeliveryMode) MarshalText() ([]byte, error) {
	switch s {
	case RemoteSkillTargetDeliveryModeAgentPull:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RemoteSkillTargetDeliveryMode) UnmarshalText(data []byte) error {
	switch RemoteSkillTargetDeliveryMode(data) {
	case RemoteSkillTargetDeliveryModeAgentPull:
		*s = RemoteSkillTargetDeliveryModeAgentPull
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/RemoteSkillTargetEnrollment
type RemoteSkillTargetEnrollment struct {
	EnrollmentCode      string            `json:"enrollment_code"`
	EnrollmentExpiresAt time.Time         `json:"enrollment_expires_at"`
	Target              RemoteSkillTarget `json:"target"`
}

// GetEnrollmentCode returns the value of EnrollmentCode.
func (s *RemoteSkillTargetEnrollment) GetEnrollmentCode() string {
	return s.EnrollmentCode
}

// GetEnrollmentExpiresAt returns the value of EnrollmentExpiresAt.
func (s *RemoteSkillTargetEnrollment) GetEnrollmentExpiresAt() time.Time {
	return s.EnrollmentExpiresAt
}

// GetTarget returns the value of Target.
func (s *RemoteSkillTargetEnrollment) GetTarget() RemoteSkillTarget {
	return s.Target
}

// SetEnrollmentCode sets the value of EnrollmentCode.
func (s *RemoteSkillTargetEnrollment) SetEnrollmentCode(val string) {
	s.EnrollmentCode = val
}

// SetEnrollmentExpiresAt sets the value of EnrollmentExpiresAt.
func (s *RemoteSkillTargetEnrollment) SetEnrollmentExpiresAt(val time.Time) {
	s.EnrollmentExpiresAt = val
}

// SetTarget sets the value of Target.
func (s *RemoteSkillTargetEnrollment) SetTarget(val RemoteSkillTarget) {
	s.Target = val
}

func (*RemoteSkillTargetEnrollment) createRemoteSkillTargetRes() {}

type RemoteSkillTargetInstallationScope string

const (
	RemoteSkillTargetInstallationScopeProject RemoteSkillTargetInstallationScope = "project"
)

// AllValues returns all RemoteSkillTargetInstallationScope values.
func (RemoteSkillTargetInstallationScope) AllValues() []RemoteSkillTargetInstallationScope {
	return []RemoteSkillTargetInstallationScope{
		RemoteSkillTargetInstallationScopeProject,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RemoteSkillTargetInstallationScope) MarshalText() ([]byte, error) {
	switch s {
	case RemoteSkillTargetInstallationScopeProject:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RemoteSkillTargetInstallationScope) UnmarshalText(data []byte) error {
	switch RemoteSkillTargetInstallationScope(data) {
	case RemoteSkillTargetInstallationScopeProject:
		*s = RemoteSkillTargetInstallationScopeProject
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/RemoteSkillTargetState
type RemoteSkillTargetState string

const (
	RemoteSkillTargetStatePending RemoteSkillTargetState = "pending"
	RemoteSkillTargetStateActive  RemoteSkillTargetState = "active"
	RemoteSkillTargetStateRevoked RemoteSkillTargetState = "revoked"
)

// AllValues returns all RemoteSkillTargetState values.
func (RemoteSkillTargetState) AllValues() []RemoteSkillTargetState {
	return []RemoteSkillTargetState{
		RemoteSkillTargetStatePending,
		RemoteSkillTargetStateActive,
		RemoteSkillTargetStateRevoked,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RemoteSkillTargetState) MarshalText() ([]byte, error) {
	switch s {
	case RemoteSkillTargetStatePending:
		return []byte(s), nil
	case RemoteSkillTargetStateActive:
		return []byte(s), nil
	case RemoteSkillTargetStateRevoked:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RemoteSkillTargetState) UnmarshalText(data []byte) error {
	switch RemoteSkillTargetState(data) {
	case RemoteSkillTargetStatePending:
		*s = RemoteSkillTargetStatePending
		return nil
	case RemoteSkillTargetStateActive:
		*s = RemoteSkillTargetStateActive
		return nil
	case RemoteSkillTargetStateRevoked:
		*s = RemoteSkillTargetStateRevoked
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/RemoteSkillTargetStatus
type RemoteSkillTargetStatus struct {
	Publications []RemoteSkillPublication `json:"publications"`
	Target       RemoteSkillTarget        `json:"target"`
}

// GetPublications returns the value of Publications.
func (s *RemoteSkillTargetStatus) GetPublications() []RemoteSkillPublication {
	return s.Publications
}

// GetTarget returns the value of Target.
func (s *RemoteSkillTargetStatus) GetTarget() RemoteSkillTarget {
	return s.Target
}

// SetPublications sets the value of Publications.
func (s *RemoteSkillTargetStatus) SetPublications(val []RemoteSkillPublication) {
	s.Publications = val
}

// SetTarget sets the value of Target.
func (s *RemoteSkillTargetStatus) SetTarget(val RemoteSkillTarget) {
	s.Target = val
}

// Ref: #/components/schemas/RenameRemoteSkillTargetRequest
type RenameRemoteSkillTargetRequest struct {
	DisplayName        string `json:"display_name"`
	ExpectedGeneration int    `json:"expected_generation"`
	ScopeID            string `json:"scope_id"`
	TargetID           string `json:"target_id"`
}

// GetDisplayName returns the value of DisplayName.
func (s *RenameRemoteSkillTargetRequest) GetDisplayName() string {
	return s.DisplayName
}

// GetExpectedGeneration returns the value of ExpectedGeneration.
func (s *RenameRemoteSkillTargetRequest) GetExpectedGeneration() int {
	return s.ExpectedGeneration
}

// GetScopeID returns the value of ScopeID.
func (s *RenameRemoteSkillTargetRequest) GetScopeID() string {
	return s.ScopeID
}

// GetTargetID returns the value of TargetID.
func (s *RenameRemoteSkillTargetRequest) GetTargetID() string {
	return s.TargetID
}

// SetDisplayName sets the value of DisplayName.
func (s *RenameRemoteSkillTargetRequest) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetExpectedGeneration sets the value of ExpectedGeneration.
func (s *RenameRemoteSkillTargetRequest) SetExpectedGeneration(val int) {
	s.ExpectedGeneration = val
}

// SetScopeID sets the value of ScopeID.
func (s *RenameRemoteSkillTargetRequest) SetScopeID(val string) {
	s.ScopeID = val
}

// SetTargetID sets the value of TargetID.
func (s *RenameRemoteSkillTargetRequest) SetTargetID(val string) {
	s.TargetID = val
}

// Ref: #/components/schemas/RevokeRemoteSkillTargetRequest
type RevokeRemoteSkillTargetRequest struct {
	ExpectedGeneration int    `json:"expected_generation"`
	ScopeID            string `json:"scope_id"`
	TargetID           string `json:"target_id"`
}

// GetExpectedGeneration returns the value of ExpectedGeneration.
func (s *RevokeRemoteSkillTargetRequest) GetExpectedGeneration() int {
	return s.ExpectedGeneration
}

// GetScopeID returns the value of ScopeID.
func (s *RevokeRemoteSkillTargetRequest) GetScopeID() string {
	return s.ScopeID
}

// GetTargetID returns the value of TargetID.
func (s *RevokeRemoteSkillTargetRequest) GetTargetID() string {
	return s.TargetID
}

// SetExpectedGeneration sets the value of ExpectedGeneration.
func (s *RevokeRemoteSkillTargetRequest) SetExpectedGeneration(val int) {
	s.ExpectedGeneration = val
}

// SetScopeID sets the value of ScopeID.
func (s *RevokeRemoteSkillTargetRequest) SetScopeID(val string) {
	s.ScopeID = val
}

// SetTargetID sets the value of TargetID.
func (s *RevokeRemoteSkillTargetRequest) SetTargetID(val string) {
	s.TargetID = val
}

// UnauthorizedHeaders wraps ErrorResponse with response headers.
type UnauthorizedHeaders struct {
	WWWAuthenticate        OptString
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetWWWAuthenticate returns the value of WWWAuthenticate.
func (s *UnauthorizedHeaders) GetWWWAuthenticate() OptString {
	return s.WWWAuthenticate
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *UnauthorizedHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *UnauthorizedHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetWWWAuthenticate sets the value of WWWAuthenticate.
func (s *UnauthorizedHeaders) SetWWWAuthenticate(val OptString) {
	s.WWWAuthenticate = val
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *UnauthorizedHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *UnauthorizedHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*UnauthorizedHeaders) createRemoteSkillTargetRes() {}
func (*UnauthorizedHeaders) listRemoteSkillTargetsRes()  {}
func (*UnauthorizedHeaders) renameRemoteSkillTargetRes() {}
func (*UnauthorizedHeaders) revokeRemoteSkillTargetRes() {}

// UnavailableHeaders wraps ErrorResponse with response headers.
type UnavailableHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *UnavailableHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *UnavailableHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *UnavailableHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *UnavailableHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*UnavailableHeaders) createRemoteSkillTargetRes() {}
func (*UnavailableHeaders) listRemoteSkillTargetsRes()  {}
