changelog:
  categories:
    - title: Breaking changes
      labels:
        - breaking
    - title: Features
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Security
      labels:
        - security
    - title: Dependencies
      labels:
        - dependencies
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - maintenance
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - wontfix
