// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"fmt"
	"hash/fnv"
)

// Hash computes a hash value for ScopeExternalReference using FNV-1a.
// Equal objects must produce equal hashes.
func (a ScopeExternalReference) Hash() uint64 {
	h := fnv.New64a()

	// Hash primitive field: Kind
	h.Write([]byte(fmt.Sprintf("%v", a.Kind)))
	// Hash primitive field: Value
	h.Write([]byte(fmt.Sprintf("%v", a.Value)))
	return h.Sum64()
}
