// Code generated by ogen, DO NOT EDIT.

package artifacts

import (
	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/ArtifactCollectionItem
type ArtifactCollectionItem struct {
	ArtifactID    string                `json:"artifact_id"`
	Artifacts     []ArtifactReference   `json:"artifacts"`
	ContentDigest string                `json:"content_digest"`
	Family        BaseArtifactFamily    `json:"family"`
	Revision      int                   `json:"revision"`
	ScopeID       string                `json:"scope_id"`
	Sources       []SourceTypeReference `json:"sources"`
}

// GetArtifactID returns the value of ArtifactID.
func (s *ArtifactCollectionItem) GetArtifactID() string {
	return s.ArtifactID
}

// GetArtifacts returns the value of Artifacts.
func (s *ArtifactCollectionItem) GetArtifacts() []ArtifactReference {
	return s.Artifacts
}

// GetContentDigest returns the value of ContentDigest.
func (s *ArtifactCollectionItem) GetContentDigest() string {
	return s.ContentDigest
}

// GetFamily returns the value of Family.
func (s *ArtifactCollectionItem) GetFamily() BaseArtifactFamily {
	return s.Family
}

// GetRevision returns the value of Revision.
func (s *ArtifactCollectionItem) GetRevision() int {
	return s.Revision
}

// GetScopeID returns the value of ScopeID.
func (s *ArtifactCollectionItem) GetScopeID() string {
	return s.ScopeID
}

// GetSources returns the value of Sources.
func (s *ArtifactCollectionItem) GetSources() []SourceTypeReference {
	return s.Sources
}

// SetArtifactID sets the value of ArtifactID.
func (s *ArtifactCollectionItem) SetArtifactID(val string) {
	s.ArtifactID = val
}

// SetArtifacts sets the value of Artifacts.
func (s *ArtifactCollectionItem) SetArtifacts(val []ArtifactReference) {
	s.Artifacts = val
}

// SetContentDigest sets the value of ContentDigest.
func (s *ArtifactCollectionItem) SetContentDigest(val string) {
	s.ContentDigest = val
}

// SetFamily sets the value of Family.
func (s *ArtifactCollectionItem) SetFamily(val BaseArtifactFamily) {
	s.Family = val
}

// SetRevision sets the value of Revision.
func (s *ArtifactCollectionItem) SetRevision(val int) {
	s.Revision = val
}

// SetScopeID sets the value of ScopeID.
func (s *ArtifactCollectionItem) SetScopeID(val string) {
	s.ScopeID = val
}

// SetSources sets the value of Sources.
func (s *ArtifactCollectionItem) SetSources(val []SourceTypeReference) {
	s.Sources = val
}

// Ref: #/components/schemas/ArtifactPage
type ArtifactPage struct {
	Items      []ArtifactCollectionItem `json:"items"`
	NextCursor NilString                `json:"next_cursor"`
}

// GetItems returns the value of Items.
func (s *ArtifactPage) GetItems() []ArtifactCollectionItem {
	return s.Items
}

// GetNextCursor returns the value of NextCursor.
func (s *ArtifactPage) GetNextCursor() NilString {
	return s.NextCursor
}

// SetItems sets the value of Items.
func (s *ArtifactPage) SetItems(val []ArtifactCollectionItem) {
	s.Items = val
}

// SetNextCursor sets the value of NextCursor.
func (s *ArtifactPage) SetNextCursor(val NilString) {
	s.NextCursor = val
}

// ArtifactPageHeaders wraps ArtifactPage with response headers.
type ArtifactPageHeaders struct {
	XPowerContextRequestID OptString
	Response               ArtifactPage
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *ArtifactPageHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *ArtifactPageHeaders) GetResponse() ArtifactPage {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *ArtifactPageHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *ArtifactPageHeaders) SetResponse(val ArtifactPage) {
	s.Response = val
}

func (*ArtifactPageHeaders) listArtifactsRes() {}

// Ref: #/components/schemas/ArtifactReference
type ArtifactReference struct {
	ArtifactID string `json:"artifact_id"`
	Family     string `json:"family"`
	Revision   int    `json:"revision"`
}

// GetArtifactID returns the value of ArtifactID.
func (s *ArtifactReference) GetArtifactID() string {
	return s.ArtifactID
}

// GetFamily returns the value of Family.
func (s *ArtifactReference) GetFamily() string {
	return s.Family
}

// GetRevision returns the value of Revision.
func (s *ArtifactReference) GetRevision() int {
	return s.Revision
}

// SetArtifactID sets the value of ArtifactID.
func (s *ArtifactReference) SetArtifactID(val string) {
	s.ArtifactID = val
}

// SetFamily sets the value of Family.
func (s *ArtifactReference) SetFamily(val string) {
	s.Family = val
}

// SetRevision sets the value of Revision.
func (s *ArtifactReference) SetRevision(val int) {
	s.Revision = val
}

// Ref: #/components/schemas/ArtifactRevision
type ArtifactRevision struct {
	ArtifactID    string                  `json:"artifact_id"`
	Artifacts     []ArtifactReference     `json:"artifacts"`
	Content       ArtifactRevisionContent `json:"content"`
	ContentDigest string                  `json:"content_digest"`
	Family        BaseArtifactFamily      `json:"family"`
	Revision      int                     `json:"revision"`
	ScopeID       string                  `json:"scope_id"`
	Sources       []SourceTypeReference   `json:"sources"`
}

// GetArtifactID returns the value of ArtifactID.
func (s *ArtifactRevision) GetArtifactID() string {
	return s.ArtifactID
}

// GetArtifacts returns the value of Artifacts.
func (s *ArtifactRevision) GetArtifacts() []ArtifactReference {
	return s.Artifacts
}

// GetContent returns the value of Content.
func (s *ArtifactRevision) GetContent() ArtifactRevisionContent {
	return s.Content
}

// GetContentDigest returns the value of ContentDigest.
func (s *ArtifactRevision) GetContentDigest() string {
	return s.ContentDigest
}

// GetFamily returns the value of Family.
func (s *ArtifactRevision) GetFamily() BaseArtifactFamily {
	return s.Family
}

// GetRevision returns the value of Revision.
func (s *ArtifactRevision) GetRevision() int {
	return s.Revision
}

// GetScopeID returns the value of ScopeID.
func (s *ArtifactRevision) GetScopeID() string {
	return s.ScopeID
}

// GetSources returns the value of Sources.
func (s *ArtifactRevision) GetSources() []SourceTypeReference {
	return s.Sources
}

// SetArtifactID sets the value of ArtifactID.
func (s *ArtifactRevision) SetArtifactID(val string) {
	s.ArtifactID = val
}

// SetArtifacts sets the value of Artifacts.
func (s *ArtifactRevision) SetArtifacts(val []ArtifactReference) {
	s.Artifacts = val
}

// SetContent sets the value of Content.
func (s *ArtifactRevision) SetContent(val ArtifactRevisionContent) {
	s.Content = val
}

// SetContentDigest sets the value of ContentDigest.
func (s *ArtifactRevision) SetContentDigest(val string) {
	s.ContentDigest = val
}

// SetFamily sets the value of Family.
func (s *ArtifactRevision) SetFamily(val BaseArtifactFamily) {
	s.Family = val
}

// SetRevision sets the value of Revision.
func (s *ArtifactRevision) SetRevision(val int) {
	s.Revision = val
}

// SetScopeID sets the value of ScopeID.
func (s *ArtifactRevision) SetScopeID(val string) {
	s.ScopeID = val
}

// SetSources sets the value of Sources.
func (s *ArtifactRevision) SetSources(val []SourceTypeReference) {
	s.Sources = val
}

type ArtifactRevisionContent map[string]jx.Raw

func (s *ArtifactRevisionContent) init() ArtifactRevisionContent {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// ArtifactRevisionHeaders wraps ArtifactRevision with response headers.
type ArtifactRevisionHeaders struct {
	ETag                   OptString
	XPowerContextRequestID OptString
	Response               ArtifactRevision
}

// GetETag returns the value of ETag.
func (s *ArtifactRevisionHeaders) GetETag() OptString {
	return s.ETag
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *ArtifactRevisionHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *ArtifactRevisionHeaders) GetResponse() ArtifactRevision {
	return s.Response
}

// SetETag sets the value of ETag.
func (s *ArtifactRevisionHeaders) SetETag(val OptString) {
	s.ETag = val
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *ArtifactRevisionHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *ArtifactRevisionHeaders) SetResponse(val ArtifactRevision) {
	s.Response = val
}

func (*ArtifactRevisionHeaders) getArtifactRes() {}

// BadRequestHeaders wraps ErrorResponse with response headers.
type BadRequestHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *BadRequestHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *BadRequestHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *BadRequestHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *BadRequestHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*BadRequestHeaders) listArtifactsRes() {}

// Ref: #/components/schemas/BaseArtifactFamily
type BaseArtifactFamily string

const (
	BaseArtifactFamilyMemory     BaseArtifactFamily = "memory"
	BaseArtifactFamilyExperience BaseArtifactFamily = "experience"
	BaseArtifactFamilySkill      BaseArtifactFamily = "skill"
	BaseArtifactFamilyHandoff    BaseArtifactFamily = "handoff"
)

// AllValues returns all BaseArtifactFamily values.
func (BaseArtifactFamily) AllValues() []BaseArtifactFamily {
	return []BaseArtifactFamily{
		BaseArtifactFamilyMemory,
		BaseArtifactFamilyExperience,
		BaseArtifactFamilySkill,
		BaseArtifactFamilyHandoff,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s BaseArtifactFamily) MarshalText() ([]byte, error) {
	switch s {
	case BaseArtifactFamilyMemory:
		return []byte(s), nil
	case BaseArtifactFamilyExperience:
		return []byte(s), nil
	case BaseArtifactFamilySkill:
		return []byte(s), nil
	case BaseArtifactFamilyHandoff:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *BaseArtifactFamily) UnmarshalText(data []byte) error {
	switch BaseArtifactFamily(data) {
	case BaseArtifactFamilyMemory:
		*s = BaseArtifactFamilyMemory
		return nil
	case BaseArtifactFamilyExperience:
		*s = BaseArtifactFamilyExperience
		return nil
	case BaseArtifactFamilySkill:
		*s = BaseArtifactFamilySkill
		return nil
	case BaseArtifactFamilyHandoff:
		*s = BaseArtifactFamilyHandoff
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// CursorExpiredHeaders wraps ErrorResponse with response headers.
type CursorExpiredHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *CursorExpiredHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *CursorExpiredHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *CursorExpiredHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *CursorExpiredHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*CursorExpiredHeaders) listArtifactsRes() {}

// Ref: #/components/schemas/ErrorDetail
type ErrorDetail struct {
	Code    string                `json:"code"`
	Details NilErrorDetailDetails `json:"details"`
	Message string                `json:"message"`
}

// GetCode returns the value of Code.
func (s *ErrorDetail) GetCode() string {
	return s.Code
}

// GetDetails returns the value of Details.
func (s *ErrorDetail) GetDetails() NilErrorDetailDetails {
	return s.Details
}

// GetMessage returns the value of Message.
func (s *ErrorDetail) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ErrorDetail) SetCode(val string) {
	s.Code = val
}

// SetDetails sets the value of Details.
func (s *ErrorDetail) SetDetails(val NilErrorDetailDetails) {
	s.Details = val
}

// SetMessage sets the value of Message.
func (s *ErrorDetail) SetMessage(val string) {
	s.Message = val
}

type ErrorDetailDetails map[string]jx.Raw

func (s *ErrorDetailDetails) init() ErrorDetailDetails {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() ErrorDetail {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val ErrorDetail) {
	s.Error = val
}

type GetArtifactFamily string

const (
	GetArtifactFamilyMemory     GetArtifactFamily = "memory"
	GetArtifactFamilyExperience GetArtifactFamily = "experience"
	GetArtifactFamilySkill      GetArtifactFamily = "skill"
	GetArtifactFamilyHandoff    GetArtifactFamily = "handoff"
)

// AllValues returns all GetArtifactFamily values.
func (GetArtifactFamily) AllValues() []GetArtifactFamily {
	return []GetArtifactFamily{
		GetArtifactFamilyMemory,
		GetArtifactFamilyExperience,
		GetArtifactFamilySkill,
		GetArtifactFamilyHandoff,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetArtifactFamily) MarshalText() ([]byte, error) {
	switch s {
	case GetArtifactFamilyMemory:
		return []byte(s), nil
	case GetArtifactFamilyExperience:
		return []byte(s), nil
	case GetArtifactFamilySkill:
		return []byte(s), nil
	case GetArtifactFamilyHandoff:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetArtifactFamily) UnmarshalText(data []byte) error {
	switch GetArtifactFamily(data) {
	case GetArtifactFamilyMemory:
		*s = GetArtifactFamilyMemory
		return nil
	case GetArtifactFamilyExperience:
		*s = GetArtifactFamilyExperience
		return nil
	case GetArtifactFamilySkill:
		*s = GetArtifactFamilySkill
		return nil
	case GetArtifactFamilyHandoff:
		*s = GetArtifactFamilyHandoff
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// GetArtifactNotModified is response for GetArtifact operation.
type GetArtifactNotModified struct {
	ETag                   OptString
	XPowerContextRequestID OptString
}

// GetETag returns the value of ETag.
func (s *GetArtifactNotModified) GetETag() OptString {
	return s.ETag
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *GetArtifactNotModified) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// SetETag sets the value of ETag.
func (s *GetArtifactNotModified) SetETag(val OptString) {
	s.ETag = val
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *GetArtifactNotModified) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

func (*GetArtifactNotModified) getArtifactRes() {}

type GetArtifactRevisionFamily string

const (
	GetArtifactRevisionFamilyMemory     GetArtifactRevisionFamily = "memory"
	GetArtifactRevisionFamilyExperience GetArtifactRevisionFamily = "experience"
	GetArtifactRevisionFamilySkill      GetArtifactRevisionFamily = "skill"
	GetArtifactRevisionFamilyHandoff    GetArtifactRevisionFamily = "handoff"
)

// AllValues returns all GetArtifactRevisionFamily values.
func (GetArtifactRevisionFamily) AllValues() []GetArtifactRevisionFamily {
	return []GetArtifactRevisionFamily{
		GetArtifactRevisionFamilyMemory,
		GetArtifactRevisionFamilyExperience,
		GetArtifactRevisionFamilySkill,
		GetArtifactRevisionFamilyHandoff,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetArtifactRevisionFamily) MarshalText() ([]byte, error) {
	switch s {
	case GetArtifactRevisionFamilyMemory:
		return []byte(s), nil
	case GetArtifactRevisionFamilyExperience:
		return []byte(s), nil
	case GetArtifactRevisionFamilySkill:
		return []byte(s), nil
	case GetArtifactRevisionFamilyHandoff:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetArtifactRevisionFamily) UnmarshalText(data []byte) error {
	switch GetArtifactRevisionFamily(data) {
	case GetArtifactRevisionFamilyMemory:
		*s = GetArtifactRevisionFamilyMemory
		return nil
	case GetArtifactRevisionFamilyExperience:
		*s = GetArtifactRevisionFamilyExperience
		return nil
	case GetArtifactRevisionFamilySkill:
		*s = GetArtifactRevisionFamilySkill
		return nil
	case GetArtifactRevisionFamilyHandoff:
		*s = GetArtifactRevisionFamilyHandoff
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// GetArtifactRevisionOKHeaders wraps ArtifactRevision with response headers.
type GetArtifactRevisionOKHeaders struct {
	XPowerContextRequestID OptString
	Response               ArtifactRevision
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *GetArtifactRevisionOKHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *GetArtifactRevisionOKHeaders) GetResponse() ArtifactRevision {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *GetArtifactRevisionOKHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *GetArtifactRevisionOKHeaders) SetResponse(val ArtifactRevision) {
	s.Response = val
}

func (*GetArtifactRevisionOKHeaders) getArtifactRevisionRes() {}

// InternalErrorHeaders wraps ErrorResponse with response headers.
type InternalErrorHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *InternalErrorHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *InternalErrorHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *InternalErrorHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *InternalErrorHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*InternalErrorHeaders) getArtifactRes()         {}
func (*InternalErrorHeaders) getArtifactRevisionRes() {}
func (*InternalErrorHeaders) listArtifactsRes()       {}

// InvalidRequestHeaders wraps ErrorResponse with response headers.
type InvalidRequestHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *InvalidRequestHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *InvalidRequestHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *InvalidRequestHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *InvalidRequestHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*InvalidRequestHeaders) getArtifactRes()         {}
func (*InvalidRequestHeaders) getArtifactRevisionRes() {}
func (*InvalidRequestHeaders) listArtifactsRes()       {}

type ListArtifactsFamily string

const (
	ListArtifactsFamilyMemory     ListArtifactsFamily = "memory"
	ListArtifactsFamilyExperience ListArtifactsFamily = "experience"
	ListArtifactsFamilySkill      ListArtifactsFamily = "skill"
	ListArtifactsFamilyHandoff    ListArtifactsFamily = "handoff"
)

// AllValues returns all ListArtifactsFamily values.
func (ListArtifactsFamily) AllValues() []ListArtifactsFamily {
	return []ListArtifactsFamily{
		ListArtifactsFamilyMemory,
		ListArtifactsFamilyExperience,
		ListArtifactsFamilySkill,
		ListArtifactsFamilyHandoff,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListArtifactsFamily) MarshalText() ([]byte, error) {
	switch s {
	case ListArtifactsFamilyMemory:
		return []byte(s), nil
	case ListArtifactsFamilyExperience:
		return []byte(s), nil
	case ListArtifactsFamilySkill:
		return []byte(s), nil
	case ListArtifactsFamilyHandoff:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListArtifactsFamily) UnmarshalText(data []byte) error {
	switch ListArtifactsFamily(data) {
	case ListArtifactsFamilyMemory:
		*s = ListArtifactsFamilyMemory
		return nil
	case ListArtifactsFamilyExperience:
		*s = ListArtifactsFamilyExperience
		return nil
	case ListArtifactsFamilySkill:
		*s = ListArtifactsFamilySkill
		return nil
	case ListArtifactsFamilyHandoff:
		*s = ListArtifactsFamilyHandoff
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewNilErrorDetailDetails returns new NilErrorDetailDetails with value set to v.
func NewNilErrorDetailDetails(v ErrorDetailDetails) NilErrorDetailDetails {
	return NilErrorDetailDetails{
		Value: v,
	}
}

// NilErrorDetailDetails is nullable ErrorDetailDetails.
type NilErrorDetailDetails struct {
	Value ErrorDetailDetails
	Null  bool
}

// SetTo sets value to v.
func (o *NilErrorDetailDetails) SetTo(v ErrorDetailDetails) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilErrorDetailDetails) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilErrorDetailDetails) SetToNull() {
	o.Null = true
	var v ErrorDetailDetails
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilErrorDetailDetails) Get() (v ErrorDetailDetails, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilErrorDetailDetails) Or(d ErrorDetailDetails) ErrorDetailDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NotFoundHeaders wraps ErrorResponse with response headers.
type NotFoundHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *NotFoundHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *NotFoundHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *NotFoundHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *NotFoundHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*NotFoundHeaders) getArtifactRes()         {}
func (*NotFoundHeaders) getArtifactRevisionRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/SourceTypeReference
type SourceTypeReference struct {
	SourceID   string                        `json:"source_id"`
	SourceType SourceTypeReferenceSourceType `json:"source_type"`
}

// GetSourceID returns the value of SourceID.
func (s *SourceTypeReference) GetSourceID() string {
	return s.SourceID
}

// GetSourceType returns the value of SourceType.
func (s *SourceTypeReference) GetSourceType() SourceTypeReferenceSourceType {
	return s.SourceType
}

// SetSourceID sets the value of SourceID.
func (s *SourceTypeReference) SetSourceID(val string) {
	s.SourceID = val
}

// SetSourceType sets the value of SourceType.
func (s *SourceTypeReference) SetSourceType(val SourceTypeReferenceSourceType) {
	s.SourceType = val
}

type SourceTypeReferenceSourceType string

const (
	SourceTypeReferenceSourceTypeContent               SourceTypeReferenceSourceType = "content"
	SourceTypeReferenceSourceTypeExternalSkillSnapshot SourceTypeReferenceSourceType = "external-skill-snapshot"
	SourceTypeReferenceSourceTypeAcceptedObservation   SourceTypeReferenceSourceType = "accepted-observation"
)

// AllValues returns all SourceTypeReferenceSourceType values.
func (SourceTypeReferenceSourceType) AllValues() []SourceTypeReferenceSourceType {
	return []SourceTypeReferenceSourceType{
		SourceTypeReferenceSourceTypeContent,
		SourceTypeReferenceSourceTypeExternalSkillSnapshot,
		SourceTypeReferenceSourceTypeAcceptedObservation,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SourceTypeReferenceSourceType) MarshalText() ([]byte, error) {
	switch s {
	case SourceTypeReferenceSourceTypeContent:
		return []byte(s), nil
	case SourceTypeReferenceSourceTypeExternalSkillSnapshot:
		return []byte(s), nil
	case SourceTypeReferenceSourceTypeAcceptedObservation:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SourceTypeReferenceSourceType) UnmarshalText(data []byte) error {
	switch SourceTypeReferenceSourceType(data) {
	case SourceTypeReferenceSourceTypeContent:
		*s = SourceTypeReferenceSourceTypeContent
		return nil
	case SourceTypeReferenceSourceTypeExternalSkillSnapshot:
		*s = SourceTypeReferenceSourceTypeExternalSkillSnapshot
		return nil
	case SourceTypeReferenceSourceTypeAcceptedObservation:
		*s = SourceTypeReferenceSourceTypeAcceptedObservation
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// UnauthorizedHeaders wraps ErrorResponse with response headers.
type UnauthorizedHeaders struct {
	WWWAuthenticate        OptString
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetWWWAuthenticate returns the value of WWWAuthenticate.
func (s *UnauthorizedHeaders) GetWWWAuthenticate() OptString {
	return s.WWWAuthenticate
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *UnauthorizedHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *UnauthorizedHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetWWWAuthenticate sets the value of WWWAuthenticate.
func (s *UnauthorizedHeaders) SetWWWAuthenticate(val OptString) {
	s.WWWAuthenticate = val
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *UnauthorizedHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *UnauthorizedHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*UnauthorizedHeaders) getArtifactRes()         {}
func (*UnauthorizedHeaders) getArtifactRevisionRes() {}
func (*UnauthorizedHeaders) listArtifactsRes()       {}

// UnavailableHeaders wraps ErrorResponse with response headers.
type UnavailableHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *UnavailableHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *UnavailableHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *UnavailableHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *UnavailableHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*UnavailableHeaders) getArtifactRes()         {}
func (*UnavailableHeaders) getArtifactRevisionRes() {}
func (*UnavailableHeaders) listArtifactsRes()       {}
