// Code generated by ogen, DO NOT EDIT.
package artifacts

type GetArtifactRes interface {
	getArtifactRes()
}

type GetArtifactRevisionRes interface {
	getArtifactRevisionRes()
}

type ListArtifactsRes interface {
	listArtifactsRes()
}
