// Code generated by ogen, DO NOT EDIT.

package artifacts

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetArtifactParams is parameters of get_artifact operation.
type GetArtifactParams struct {
	ScopeID     string
	Family      GetArtifactFamily
	ArtifactID  string
	IfNoneMatch OptString `json:",omitempty,omitzero"`
}

func unpackGetArtifactParams(packed middleware.Parameters) (params GetArtifactParams) {
	{
		key := middleware.ParameterKey{
			Name: "scope_id",
			In:   "path",
		}
		params.ScopeID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "family",
			In:   "path",
		}
		params.Family = packed[key].(GetArtifactFamily)
	}
	{
		key := middleware.ParameterKey{
			Name: "artifact_id",
			In:   "path",
		}
		params.ArtifactID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "If-None-Match",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.IfNoneMatch = v.(OptString)
		}
	}
	return params
}

func decodeGetArtifactParams(args [3]string, argsEscaped bool, r *http.Request) (params GetArtifactParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode path: scope_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "scope_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ScopeID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     256,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap[".*\\S.*"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.ScopeID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "scope_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: family.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "family",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Family = GetArtifactFamily(c)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Family.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "family",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: artifact_id.
	if err := func() error {
		param := args[2]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[2])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "artifact_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ArtifactID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^[\\x21-\\x7E]+$"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.ArtifactID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "artifact_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: If-None-Match.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "If-None-Match",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIfNoneMatchVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotIfNoneMatchVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IfNoneMatch.SetTo(paramsDotIfNoneMatchVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.IfNoneMatch.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     1,
							MinLengthSet:  true,
							MaxLength:     0,
							MaxLengthSet:  false,
							Email:         false,
							Hostname:      false,
							Regex:         nil,
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "If-None-Match",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// GetArtifactRevisionParams is parameters of get_artifact_revision operation.
type GetArtifactRevisionParams struct {
	ScopeID    string
	Family     GetArtifactRevisionFamily
	ArtifactID string
	Revision   int
}

func unpackGetArtifactRevisionParams(packed middleware.Parameters) (params GetArtifactRevisionParams) {
	{
		key := middleware.ParameterKey{
			Name: "scope_id",
			In:   "path",
		}
		params.ScopeID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "family",
			In:   "path",
		}
		params.Family = packed[key].(GetArtifactRevisionFamily)
	}
	{
		key := middleware.ParameterKey{
			Name: "artifact_id",
			In:   "path",
		}
		params.ArtifactID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "revision",
			In:   "path",
		}
		params.Revision = packed[key].(int)
	}
	return params
}

func decodeGetArtifactRevisionParams(args [4]string, argsEscaped bool, r *http.Request) (params GetArtifactRevisionParams, _ error) {
	// Decode path: scope_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "scope_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ScopeID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     256,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap[".*\\S.*"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.ScopeID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "scope_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: family.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "family",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Family = GetArtifactRevisionFamily(c)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Family.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "family",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: artifact_id.
	if err := func() error {
		param := args[2]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[2])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "artifact_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ArtifactID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^[\\x21-\\x7E]+$"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.ArtifactID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "artifact_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: revision.
	if err := func() error {
		param := args[3]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[3])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "revision",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.Revision = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           1,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(params.Revision)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "revision",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
