// Code generated by ogen, DO NOT EDIT.

package stats

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetStats implements get_stats operation.
//
// Aggregate product statistics over a Scope selection.
//
// POST /v1/stats
func (UnimplementedHandler) GetStats(ctx context.Context, req *GetStatsRequest) (r GetStatsRes, _ error) {
	return r, ht.ErrNotImplemented
}
