// Code generated by ogen, DO NOT EDIT.

package stats

// setDefaults set default value of fields.
func (s *GetStatsRequest) setDefaults() {
	{
		val := StatsPeriod("30d")
		s.Period.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ResolvedUsagePeriod) setDefaults() {
	{
		val := StatsPeriod("30d")
		s.Preset = val
	}
}
