// Code generated by ogen, DO NOT EDIT.

package scopes

// setDefaults set default value of fields.
func (s *ResolveScopeBindingRequest) setDefaults() {
	{
		var defaultVal0 []ScopeBindingKey
		s.BindingKeys = defaultVal0
	}
}
