// Code generated by ogen, DO NOT EDIT.

package scopes

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetDefaultScope implements get_default_scope operation.
	//
	// Get the default Scope binding target.
	//
	// GET /v1/scopes/default
	GetDefaultScope(ctx context.Context) (GetDefaultScopeRes, error)
	// GetScope implements get_scope operation.
	//
	// Get one Scope descriptor.
	//
	// GET /v1/scopes/{scope_id}
	GetScope(ctx context.Context, params GetScopeParams) (GetScopeRes, error)
	// ListScopes implements list_scopes operation.
	//
	// List observable Scopes.
	//
	// GET /v1/scopes
	ListScopes(ctx context.Context) (ListScopesRes, error)
	// ResolveScopeBinding implements resolve_scope_binding operation.
	//
	// Resolve an explicit durable or default Scope binding.
	//
	// POST /v1/scope-bindings/resolve
	ResolveScopeBinding(ctx context.Context, req *ResolveScopeBindingRequest) (ResolveScopeBindingRes, error)
	// ResolveScopeSelection implements resolve_scope_selection operation.
	//
	// Resolve an observation selection to a frozen Scope set.
	//
	// POST /v1/scopes/selection/resolve
	ResolveScopeSelection(ctx context.Context, req *ResolveScopeSelectionRequest) (ResolveScopeSelectionRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
