// Code generated by ogen, DO NOT EDIT.

package sources

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateSource implements create_source operation.
	//
	// Persist one Source without synchronously deriving Artifacts. The Server generates source_id.
	//
	// POST /v1/scopes/{scope_id}/sources
	CreateSource(ctx context.Context, req *CreateSourceRequest, params CreateSourceParams) (CreateSourceRes, error)
	// GetSource implements get_source operation.
	//
	// Get one exact Source.
	//
	// GET /v1/scopes/{scope_id}/sources/{source_type}/{source_id}
	GetSource(ctx context.Context, params GetSourceParams) (GetSourceRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
