// Code generated by ogen, DO NOT EDIT.

package sources

import (
	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// ConflictHeaders wraps ErrorResponse with response headers.
type ConflictHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *ConflictHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *ConflictHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *ConflictHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *ConflictHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*ConflictHeaders) createSourceRes() {}

// Ref: #/components/schemas/CreateSourceRequest
type CreateSourceRequest struct {
	// JSON value persisted by the built-in content Source adapter.
	Content    jx.Raw                           `json:"content"`
	SourceType OptCreateSourceRequestSourceType `json:"source_type"`
}

// GetContent returns the value of Content.
func (s *CreateSourceRequest) GetContent() jx.Raw {
	return s.Content
}

// GetSourceType returns the value of SourceType.
func (s *CreateSourceRequest) GetSourceType() OptCreateSourceRequestSourceType {
	return s.SourceType
}

// SetContent sets the value of Content.
func (s *CreateSourceRequest) SetContent(val jx.Raw) {
	s.Content = val
}

// SetSourceType sets the value of SourceType.
func (s *CreateSourceRequest) SetSourceType(val OptCreateSourceRequestSourceType) {
	s.SourceType = val
}

type CreateSourceRequestSourceType string

const (
	CreateSourceRequestSourceTypeContent CreateSourceRequestSourceType = "content"
)

// AllValues returns all CreateSourceRequestSourceType values.
func (CreateSourceRequestSourceType) AllValues() []CreateSourceRequestSourceType {
	return []CreateSourceRequestSourceType{
		CreateSourceRequestSourceTypeContent,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateSourceRequestSourceType) MarshalText() ([]byte, error) {
	switch s {
	case CreateSourceRequestSourceTypeContent:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateSourceRequestSourceType) UnmarshalText(data []byte) error {
	switch CreateSourceRequestSourceType(data) {
	case CreateSourceRequestSourceTypeContent:
		*s = CreateSourceRequestSourceTypeContent
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ErrorDetail
type ErrorDetail struct {
	Code    string                `json:"code"`
	Details NilErrorDetailDetails `json:"details"`
	Message string                `json:"message"`
}

// GetCode returns the value of Code.
func (s *ErrorDetail) GetCode() string {
	return s.Code
}

// GetDetails returns the value of Details.
func (s *ErrorDetail) GetDetails() NilErrorDetailDetails {
	return s.Details
}

// GetMessage returns the value of Message.
func (s *ErrorDetail) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ErrorDetail) SetCode(val string) {
	s.Code = val
}

// SetDetails sets the value of Details.
func (s *ErrorDetail) SetDetails(val NilErrorDetailDetails) {
	s.Details = val
}

// SetMessage sets the value of Message.
func (s *ErrorDetail) SetMessage(val string) {
	s.Message = val
}

type ErrorDetailDetails map[string]jx.Raw

func (s *ErrorDetailDetails) init() ErrorDetailDetails {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() ErrorDetail {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val ErrorDetail) {
	s.Error = val
}

// GetSourceOKHeaders wraps SourceRecord with response headers.
type GetSourceOKHeaders struct {
	XPowerContextRequestID OptString
	Response               SourceRecord
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *GetSourceOKHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *GetSourceOKHeaders) GetResponse() SourceRecord {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *GetSourceOKHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *GetSourceOKHeaders) SetResponse(val SourceRecord) {
	s.Response = val
}

func (*GetSourceOKHeaders) getSourceRes() {}

type GetSourceSourceType string

const (
	GetSourceSourceTypeContent GetSourceSourceType = "content"
)

// AllValues returns all GetSourceSourceType values.
func (GetSourceSourceType) AllValues() []GetSourceSourceType {
	return []GetSourceSourceType{
		GetSourceSourceTypeContent,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetSourceSourceType) MarshalText() ([]byte, error) {
	switch s {
	case GetSourceSourceTypeContent:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetSourceSourceType) UnmarshalText(data []byte) error {
	switch GetSourceSourceType(data) {
	case GetSourceSourceTypeContent:
		*s = GetSourceSourceTypeContent
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// InternalErrorHeaders wraps ErrorResponse with response headers.
type InternalErrorHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *InternalErrorHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *InternalErrorHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *InternalErrorHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *InternalErrorHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*InternalErrorHeaders) createSourceRes() {}
func (*InternalErrorHeaders) getSourceRes()    {}

// InvalidRequestHeaders wraps ErrorResponse with response headers.
type InvalidRequestHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *InvalidRequestHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *InvalidRequestHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *InvalidRequestHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *InvalidRequestHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*InvalidRequestHeaders) createSourceRes() {}
func (*InvalidRequestHeaders) getSourceRes()    {}

// NewNilErrorDetailDetails returns new NilErrorDetailDetails with value set to v.
func NewNilErrorDetailDetails(v ErrorDetailDetails) NilErrorDetailDetails {
	return NilErrorDetailDetails{
		Value: v,
	}
}

// NilErrorDetailDetails is nullable ErrorDetailDetails.
type NilErrorDetailDetails struct {
	Value ErrorDetailDetails
	Null  bool
}

// SetTo sets value to v.
func (o *NilErrorDetailDetails) SetTo(v ErrorDetailDetails) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilErrorDetailDetails) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilErrorDetailDetails) SetToNull() {
	o.Null = true
	var v ErrorDetailDetails
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilErrorDetailDetails) Get() (v ErrorDetailDetails, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilErrorDetailDetails) Or(d ErrorDetailDetails) ErrorDetailDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NotFoundHeaders wraps ErrorResponse with response headers.
type NotFoundHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *NotFoundHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *NotFoundHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *NotFoundHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *NotFoundHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*NotFoundHeaders) getSourceRes() {}

// NewOptCreateSourceRequestSourceType returns new OptCreateSourceRequestSourceType with value set to v.
func NewOptCreateSourceRequestSourceType(v CreateSourceRequestSourceType) OptCreateSourceRequestSourceType {
	return OptCreateSourceRequestSourceType{
		Value: v,
		Set:   true,
	}
}

// OptCreateSourceRequestSourceType is optional CreateSourceRequestSourceType.
type OptCreateSourceRequestSourceType struct {
	Value CreateSourceRequestSourceType
	Set   bool
}

// IsSet returns true if OptCreateSourceRequestSourceType was set.
func (o OptCreateSourceRequestSourceType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateSourceRequestSourceType) Reset() {
	var v CreateSourceRequestSourceType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateSourceRequestSourceType) SetTo(v CreateSourceRequestSourceType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateSourceRequestSourceType) Get() (v CreateSourceRequestSourceType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateSourceRequestSourceType) Or(d CreateSourceRequestSourceType) CreateSourceRequestSourceType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/SourceRecord
type SourceRecord struct {
	// Persisted canonical JSON content.
	Content       jx.Raw                 `json:"content"`
	ContentDigest string                 `json:"content_digest"`
	Position      int                    `json:"position"`
	ScopeID       string                 `json:"scope_id"`
	SourceID      string                 `json:"source_id"`
	SourceType    SourceRecordSourceType `json:"source_type"`
}

// GetContent returns the value of Content.
func (s *SourceRecord) GetContent() jx.Raw {
	return s.Content
}

// GetContentDigest returns the value of ContentDigest.
func (s *SourceRecord) GetContentDigest() string {
	return s.ContentDigest
}

// GetPosition returns the value of Position.
func (s *SourceRecord) GetPosition() int {
	return s.Position
}

// GetScopeID returns the value of ScopeID.
func (s *SourceRecord) GetScopeID() string {
	return s.ScopeID
}

// GetSourceID returns the value of SourceID.
func (s *SourceRecord) GetSourceID() string {
	return s.SourceID
}

// GetSourceType returns the value of SourceType.
func (s *SourceRecord) GetSourceType() SourceRecordSourceType {
	return s.SourceType
}

// SetContent sets the value of Content.
func (s *SourceRecord) SetContent(val jx.Raw) {
	s.Content = val
}

// SetContentDigest sets the value of ContentDigest.
func (s *SourceRecord) SetContentDigest(val string) {
	s.ContentDigest = val
}

// SetPosition sets the value of Position.
func (s *SourceRecord) SetPosition(val int) {
	s.Position = val
}

// SetScopeID sets the value of ScopeID.
func (s *SourceRecord) SetScopeID(val string) {
	s.ScopeID = val
}

// SetSourceID sets the value of SourceID.
func (s *SourceRecord) SetSourceID(val string) {
	s.SourceID = val
}

// SetSourceType sets the value of SourceType.
func (s *SourceRecord) SetSourceType(val SourceRecordSourceType) {
	s.SourceType = val
}

// SourceRecordHeaders wraps SourceRecord with response headers.
type SourceRecordHeaders struct {
	Location               OptString
	XPowerContextRequestID OptString
	Response               SourceRecord
}

// GetLocation returns the value of Location.
func (s *SourceRecordHeaders) GetLocation() OptString {
	return s.Location
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *SourceRecordHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *SourceRecordHeaders) GetResponse() SourceRecord {
	return s.Response
}

// SetLocation sets the value of Location.
func (s *SourceRecordHeaders) SetLocation(val OptString) {
	s.Location = val
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *SourceRecordHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *SourceRecordHeaders) SetResponse(val SourceRecord) {
	s.Response = val
}

func (*SourceRecordHeaders) createSourceRes() {}

type SourceRecordSourceType string

const (
	SourceRecordSourceTypeContent SourceRecordSourceType = "content"
)

// AllValues returns all SourceRecordSourceType values.
func (SourceRecordSourceType) AllValues() []SourceRecordSourceType {
	return []SourceRecordSourceType{
		SourceRecordSourceTypeContent,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SourceRecordSourceType) MarshalText() ([]byte, error) {
	switch s {
	case SourceRecordSourceTypeContent:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SourceRecordSourceType) UnmarshalText(data []byte) error {
	switch SourceRecordSourceType(data) {
	case SourceRecordSourceTypeContent:
		*s = SourceRecordSourceTypeContent
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// UnauthorizedHeaders wraps ErrorResponse with response headers.
type UnauthorizedHeaders struct {
	WWWAuthenticate        OptString
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetWWWAuthenticate returns the value of WWWAuthenticate.
func (s *UnauthorizedHeaders) GetWWWAuthenticate() OptString {
	return s.WWWAuthenticate
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *UnauthorizedHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *UnauthorizedHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetWWWAuthenticate sets the value of WWWAuthenticate.
func (s *UnauthorizedHeaders) SetWWWAuthenticate(val OptString) {
	s.WWWAuthenticate = val
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *UnauthorizedHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *UnauthorizedHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*UnauthorizedHeaders) createSourceRes() {}
func (*UnauthorizedHeaders) getSourceRes()    {}

// UnavailableHeaders wraps ErrorResponse with response headers.
type UnavailableHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *UnavailableHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *UnavailableHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *UnavailableHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *UnavailableHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*UnavailableHeaders) createSourceRes() {}
func (*UnavailableHeaders) getSourceRes()    {}
