// Code generated by ogen, DO NOT EDIT.
package managedskills

type DownloadSkillPackageRes interface {
	downloadSkillPackageRes()
}

type GetSkillPackageManifestRes interface {
	getSkillPackageManifestRes()
}
