// Code generated by ogen, DO NOT EDIT.

package managedskills

import (
	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/ArtifactCandidate
type ArtifactCandidate struct {
	// Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.
	ArtifactRefs   []ArtifactReference       `json:"artifact_refs"`
	CandidateID    string                    `json:"candidate_id"`
	DecisionReason NilString                 `json:"decision_reason"`
	Family         CandidateFamily           `json:"family"`
	Proposal       ArtifactCandidateProposal `json:"proposal"`
	Reason         NilString                 `json:"reason"`
	ResultArtifact NilArtifactReference      `json:"result_artifact"`
	// Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.
	SourceRefs []SourceReference    `json:"source_refs"`
	Status     CandidateStatus      `json:"status"`
	Target     NilArtifactReference `json:"target"`
	Version    int                  `json:"version"`
}

// GetArtifactRefs returns the value of ArtifactRefs.
func (s *ArtifactCandidate) GetArtifactRefs() []ArtifactReference {
	return s.ArtifactRefs
}

// GetCandidateID returns the value of CandidateID.
func (s *ArtifactCandidate) GetCandidateID() string {
	return s.CandidateID
}

// GetDecisionReason returns the value of DecisionReason.
func (s *ArtifactCandidate) GetDecisionReason() NilString {
	return s.DecisionReason
}

// GetFamily returns the value of Family.
func (s *ArtifactCandidate) GetFamily() CandidateFamily {
	return s.Family
}

// GetProposal returns the value of Proposal.
func (s *ArtifactCandidate) GetProposal() ArtifactCandidateProposal {
	return s.Proposal
}

// GetReason returns the value of Reason.
func (s *ArtifactCandidate) GetReason() NilString {
	return s.Reason
}

// GetResultArtifact returns the value of ResultArtifact.
func (s *ArtifactCandidate) GetResultArtifact() NilArtifactReference {
	return s.ResultArtifact
}

// GetSourceRefs returns the value of SourceRefs.
func (s *ArtifactCandidate) GetSourceRefs() []SourceReference {
	return s.SourceRefs
}

// GetStatus returns the value of Status.
func (s *ArtifactCandidate) GetStatus() CandidateStatus {
	return s.Status
}

// GetTarget returns the value of Target.
func (s *ArtifactCandidate) GetTarget() NilArtifactReference {
	return s.Target
}

// GetVersion returns the value of Version.
func (s *ArtifactCandidate) GetVersion() int {
	return s.Version
}

// SetArtifactRefs sets the value of ArtifactRefs.
func (s *ArtifactCandidate) SetArtifactRefs(val []ArtifactReference) {
	s.ArtifactRefs = val
}

// SetCandidateID sets the value of CandidateID.
func (s *ArtifactCandidate) SetCandidateID(val string) {
	s.CandidateID = val
}

// SetDecisionReason sets the value of DecisionReason.
func (s *ArtifactCandidate) SetDecisionReason(val NilString) {
	s.DecisionReason = val
}

// SetFamily sets the value of Family.
func (s *ArtifactCandidate) SetFamily(val CandidateFamily) {
	s.Family = val
}

// SetProposal sets the value of Proposal.
func (s *ArtifactCandidate) SetProposal(val ArtifactCandidateProposal) {
	s.Proposal = val
}

// SetReason sets the value of Reason.
func (s *ArtifactCandidate) SetReason(val NilString) {
	s.Reason = val
}

// SetResultArtifact sets the value of ResultArtifact.
func (s *ArtifactCandidate) SetResultArtifact(val NilArtifactReference) {
	s.ResultArtifact = val
}

// SetSourceRefs sets the value of SourceRefs.
func (s *ArtifactCandidate) SetSourceRefs(val []SourceReference) {
	s.SourceRefs = val
}

// SetStatus sets the value of Status.
func (s *ArtifactCandidate) SetStatus(val CandidateStatus) {
	s.Status = val
}

// SetTarget sets the value of Target.
func (s *ArtifactCandidate) SetTarget(val NilArtifactReference) {
	s.Target = val
}

// SetVersion sets the value of Version.
func (s *ArtifactCandidate) SetVersion(val int) {
	s.Version = val
}

func (*ArtifactCandidate) proposeSkillPackageRes() {}

// ArtifactCandidateProposal represents sum type.
type ArtifactCandidateProposal struct {
	// Type selects the active sum variant, switch on this field.
	Type               ArtifactCandidateProposalType
	ExperienceProposal ExperienceProposal
	SkillProposal      SkillProposal
}

// ArtifactCandidateProposalType is oneOf type of ArtifactCandidateProposal.
type ArtifactCandidateProposalType string

// Possible values for ArtifactCandidateProposalType.
const (
	ExperienceProposalArtifactCandidateProposal ArtifactCandidateProposalType = "ExperienceProposal"
	SkillProposalArtifactCandidateProposal      ArtifactCandidateProposalType = "SkillProposal"
)

// IsExperienceProposal reports whether ArtifactCandidateProposal is ExperienceProposal.
func (s ArtifactCandidateProposal) IsExperienceProposal() bool {
	return s.Type == ExperienceProposalArtifactCandidateProposal
}

// IsSkillProposal reports whether ArtifactCandidateProposal is SkillProposal.
func (s ArtifactCandidateProposal) IsSkillProposal() bool {
	return s.Type == SkillProposalArtifactCandidateProposal
}

// SetExperienceProposal sets ArtifactCandidateProposal to ExperienceProposal.
func (s *ArtifactCandidateProposal) SetExperienceProposal(v ExperienceProposal) {
	s.Type = ExperienceProposalArtifactCandidateProposal
	s.ExperienceProposal = v
}

// GetExperienceProposal returns ExperienceProposal and true boolean if ArtifactCandidateProposal is ExperienceProposal.
func (s ArtifactCandidateProposal) GetExperienceProposal() (v ExperienceProposal, ok bool) {
	if !s.IsExperienceProposal() {
		return v, false
	}
	return s.ExperienceProposal, true
}

// NewExperienceProposalArtifactCandidateProposal returns new ArtifactCandidateProposal from ExperienceProposal.
func NewExperienceProposalArtifactCandidateProposal(v ExperienceProposal) ArtifactCandidateProposal {
	var s ArtifactCandidateProposal
	s.SetExperienceProposal(v)
	return s
}

// SetSkillProposal sets ArtifactCandidateProposal to SkillProposal.
func (s *ArtifactCandidateProposal) SetSkillProposal(v SkillProposal) {
	s.Type = SkillProposalArtifactCandidateProposal
	s.SkillProposal = v
}

// GetSkillProposal returns SkillProposal and true boolean if ArtifactCandidateProposal is SkillProposal.
func (s ArtifactCandidateProposal) GetSkillProposal() (v SkillProposal, ok bool) {
	if !s.IsSkillProposal() {
		return v, false
	}
	return s.SkillProposal, true
}

// NewSkillProposalArtifactCandidateProposal returns new ArtifactCandidateProposal from SkillProposal.
func NewSkillProposalArtifactCandidateProposal(v SkillProposal) ArtifactCandidateProposal {
	var s ArtifactCandidateProposal
	s.SetSkillProposal(v)
	return s
}

// Ref: #/components/schemas/ArtifactReference
type ArtifactReference struct {
	ArtifactID string `json:"artifact_id"`
	Family     string `json:"family"`
	Revision   int    `json:"revision"`
}

// GetArtifactID returns the value of ArtifactID.
func (s *ArtifactReference) GetArtifactID() string {
	return s.ArtifactID
}

// GetFamily returns the value of Family.
func (s *ArtifactReference) GetFamily() string {
	return s.Family
}

// GetRevision returns the value of Revision.
func (s *ArtifactReference) GetRevision() int {
	return s.Revision
}

// SetArtifactID sets the value of ArtifactID.
func (s *ArtifactReference) SetArtifactID(val string) {
	s.ArtifactID = val
}

// SetFamily sets the value of Family.
func (s *ArtifactReference) SetFamily(val string) {
	s.Family = val
}

// SetRevision sets the value of Revision.
func (s *ArtifactReference) SetRevision(val int) {
	s.Revision = val
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/CandidateFamily
type CandidateFamily string

const (
	CandidateFamilyExperience CandidateFamily = "experience"
	CandidateFamilySkill      CandidateFamily = "skill"
)

// AllValues returns all CandidateFamily values.
func (CandidateFamily) AllValues() []CandidateFamily {
	return []CandidateFamily{
		CandidateFamilyExperience,
		CandidateFamilySkill,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CandidateFamily) MarshalText() ([]byte, error) {
	switch s {
	case CandidateFamilyExperience:
		return []byte(s), nil
	case CandidateFamilySkill:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CandidateFamily) UnmarshalText(data []byte) error {
	switch CandidateFamily(data) {
	case CandidateFamilyExperience:
		*s = CandidateFamilyExperience
		return nil
	case CandidateFamilySkill:
		*s = CandidateFamilySkill
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CandidateStatus
type CandidateStatus string

const (
	CandidateStatusPending  CandidateStatus = "pending"
	CandidateStatusApproved CandidateStatus = "approved"
	CandidateStatusRejected CandidateStatus = "rejected"
)

// AllValues returns all CandidateStatus values.
func (CandidateStatus) AllValues() []CandidateStatus {
	return []CandidateStatus{
		CandidateStatusPending,
		CandidateStatusApproved,
		CandidateStatusRejected,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CandidateStatus) MarshalText() ([]byte, error) {
	switch s {
	case CandidateStatusPending:
		return []byte(s), nil
	case CandidateStatusApproved:
		return []byte(s), nil
	case CandidateStatusRejected:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CandidateStatus) UnmarshalText(data []byte) error {
	switch CandidateStatus(data) {
	case CandidateStatusPending:
		*s = CandidateStatusPending
		return nil
	case CandidateStatusApproved:
		*s = CandidateStatusApproved
		return nil
	case CandidateStatusRejected:
		*s = CandidateStatusRejected
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CaptureContentSourceResponse
type CaptureContentSourceResponse struct {
	Position int             `json:"position"`
	Source   SourceReference `json:"source"`
	Status   CaptureStatus   `json:"status"`
}

// GetPosition returns the value of Position.
func (s *CaptureContentSourceResponse) GetPosition() int {
	return s.Position
}

// GetSource returns the value of Source.
func (s *CaptureContentSourceResponse) GetSource() SourceReference {
	return s.Source
}

// GetStatus returns the value of Status.
func (s *CaptureContentSourceResponse) GetStatus() CaptureStatus {
	return s.Status
}

// SetPosition sets the value of Position.
func (s *CaptureContentSourceResponse) SetPosition(val int) {
	s.Position = val
}

// SetSource sets the value of Source.
func (s *CaptureContentSourceResponse) SetSource(val SourceReference) {
	s.Source = val
}

// SetStatus sets the value of Status.
func (s *CaptureContentSourceResponse) SetStatus(val CaptureStatus) {
	s.Status = val
}

func (*CaptureContentSourceResponse) recordSkillUsageRes() {}

// Ref: #/components/schemas/CaptureStatus
type CaptureStatus string

const (
	CaptureStatusAccepted CaptureStatus = "accepted"
)

// AllValues returns all CaptureStatus values.
func (CaptureStatus) AllValues() []CaptureStatus {
	return []CaptureStatus{
		CaptureStatusAccepted,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CaptureStatus) MarshalText() ([]byte, error) {
	switch s {
	case CaptureStatusAccepted:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CaptureStatus) UnmarshalText(data []byte) error {
	switch CaptureStatus(data) {
	case CaptureStatusAccepted:
		*s = CaptureStatusAccepted
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// ConflictHeaders wraps ErrorResponse with response headers.
type ConflictHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *ConflictHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *ConflictHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *ConflictHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *ConflictHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*ConflictHeaders) proposeSkillPackageRes() {}
func (*ConflictHeaders) recordSkillUsageRes()    {}

// Ref: #/components/schemas/ErrorDetail
type ErrorDetail struct {
	Code    string                `json:"code"`
	Details NilErrorDetailDetails `json:"details"`
	Message string                `json:"message"`
}

// GetCode returns the value of Code.
func (s *ErrorDetail) GetCode() string {
	return s.Code
}

// GetDetails returns the value of Details.
func (s *ErrorDetail) GetDetails() NilErrorDetailDetails {
	return s.Details
}

// GetMessage returns the value of Message.
func (s *ErrorDetail) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ErrorDetail) SetCode(val string) {
	s.Code = val
}

// SetDetails sets the value of Details.
func (s *ErrorDetail) SetDetails(val NilErrorDetailDetails) {
	s.Details = val
}

// SetMessage sets the value of Message.
func (s *ErrorDetail) SetMessage(val string) {
	s.Message = val
}

type ErrorDetailDetails map[string]jx.Raw

func (s *ErrorDetailDetails) init() ErrorDetailDetails {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() ErrorDetail {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val ErrorDetail) {
	s.Error = val
}

// Ref: #/components/schemas/ExperienceProposal
type ExperienceProposal struct {
	Action    string `json:"action"`
	Lesson    string `json:"lesson"`
	Outcome   string `json:"outcome"`
	Situation string `json:"situation"`
}

// GetAction returns the value of Action.
func (s *ExperienceProposal) GetAction() string {
	return s.Action
}

// GetLesson returns the value of Lesson.
func (s *ExperienceProposal) GetLesson() string {
	return s.Lesson
}

// GetOutcome returns the value of Outcome.
func (s *ExperienceProposal) GetOutcome() string {
	return s.Outcome
}

// GetSituation returns the value of Situation.
func (s *ExperienceProposal) GetSituation() string {
	return s.Situation
}

// SetAction sets the value of Action.
func (s *ExperienceProposal) SetAction(val string) {
	s.Action = val
}

// SetLesson sets the value of Lesson.
func (s *ExperienceProposal) SetLesson(val string) {
	s.Lesson = val
}

// SetOutcome sets the value of Outcome.
func (s *ExperienceProposal) SetOutcome(val string) {
	s.Outcome = val
}

// SetSituation sets the value of Situation.
func (s *ExperienceProposal) SetSituation(val string) {
	s.Situation = val
}

// Ref: #/components/schemas/GetSkillPackageRequest
type GetSkillPackageRequest struct {
	Artifact ArtifactReference `json:"artifact"`
	ScopeID  string            `json:"scope_id"`
}

// GetArtifact returns the value of Artifact.
func (s *GetSkillPackageRequest) GetArtifact() ArtifactReference {
	return s.Artifact
}

// GetScopeID returns the value of ScopeID.
func (s *GetSkillPackageRequest) GetScopeID() string {
	return s.ScopeID
}

// SetArtifact sets the value of Artifact.
func (s *GetSkillPackageRequest) SetArtifact(val ArtifactReference) {
	s.Artifact = val
}

// SetScopeID sets the value of ScopeID.
func (s *GetSkillPackageRequest) SetScopeID(val string) {
	s.ScopeID = val
}

// InternalErrorHeaders wraps ErrorResponse with response headers.
type InternalErrorHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *InternalErrorHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *InternalErrorHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *InternalErrorHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *InternalErrorHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*InternalErrorHeaders) downloadSkillPackageRes()    {}
func (*InternalErrorHeaders) getSkillPackageManifestRes() {}
func (*InternalErrorHeaders) proposeSkillPackageRes()     {}
func (*InternalErrorHeaders) recordSkillUsageRes()        {}

// InvalidRequestHeaders wraps ErrorResponse with response headers.
type InvalidRequestHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *InvalidRequestHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *InvalidRequestHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *InvalidRequestHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *InvalidRequestHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*InvalidRequestHeaders) downloadSkillPackageRes()    {}
func (*InvalidRequestHeaders) getSkillPackageManifestRes() {}
func (*InvalidRequestHeaders) proposeSkillPackageRes()     {}
func (*InvalidRequestHeaders) recordSkillUsageRes()        {}

// NewNilArtifactReference returns new NilArtifactReference with value set to v.
func NewNilArtifactReference(v ArtifactReference) NilArtifactReference {
	return NilArtifactReference{
		Value: v,
	}
}

// NilArtifactReference is nullable ArtifactReference.
type NilArtifactReference struct {
	Value ArtifactReference
	Null  bool
}

// SetTo sets value to v.
func (o *NilArtifactReference) SetTo(v ArtifactReference) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilArtifactReference) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilArtifactReference) SetToNull() {
	o.Null = true
	var v ArtifactReference
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilArtifactReference) Get() (v ArtifactReference, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilArtifactReference) Or(d ArtifactReference) ArtifactReference {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilErrorDetailDetails returns new NilErrorDetailDetails with value set to v.
func NewNilErrorDetailDetails(v ErrorDetailDetails) NilErrorDetailDetails {
	return NilErrorDetailDetails{
		Value: v,
	}
}

// NilErrorDetailDetails is nullable ErrorDetailDetails.
type NilErrorDetailDetails struct {
	Value ErrorDetailDetails
	Null  bool
}

// SetTo sets value to v.
func (o *NilErrorDetailDetails) SetTo(v ErrorDetailDetails) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilErrorDetailDetails) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilErrorDetailDetails) SetToNull() {
	o.Null = true
	var v ErrorDetailDetails
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilErrorDetailDetails) Get() (v ErrorDetailDetails, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilErrorDetailDetails) Or(d ErrorDetailDetails) ErrorDetailDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NotFoundHeaders wraps ErrorResponse with response headers.
type NotFoundHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *NotFoundHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *NotFoundHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *NotFoundHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *NotFoundHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*NotFoundHeaders) downloadSkillPackageRes()    {}
func (*NotFoundHeaders) getSkillPackageManifestRes() {}
func (*NotFoundHeaders) recordSkillUsageRes()        {}

// NewOptArtifactReference returns new OptArtifactReference with value set to v.
func NewOptArtifactReference(v ArtifactReference) OptArtifactReference {
	return OptArtifactReference{
		Value: v,
		Set:   true,
	}
}

// OptArtifactReference is optional ArtifactReference.
type OptArtifactReference struct {
	Value ArtifactReference
	Set   bool
}

// IsSet returns true if OptArtifactReference was set.
func (o OptArtifactReference) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptArtifactReference) Reset() {
	var v ArtifactReference
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptArtifactReference) SetTo(v ArtifactReference) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptArtifactReference) Get() (v ArtifactReference, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptArtifactReference) Or(d ArtifactReference) ArtifactReference {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSkillPackageReference returns new OptSkillPackageReference with value set to v.
func NewOptSkillPackageReference(v SkillPackageReference) OptSkillPackageReference {
	return OptSkillPackageReference{
		Value: v,
		Set:   true,
	}
}

// OptSkillPackageReference is optional SkillPackageReference.
type OptSkillPackageReference struct {
	Value SkillPackageReference
	Set   bool
}

// IsSet returns true if OptSkillPackageReference was set.
func (o OptSkillPackageReference) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSkillPackageReference) Reset() {
	var v SkillPackageReference
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSkillPackageReference) SetTo(v SkillPackageReference) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSkillPackageReference) Get() (v SkillPackageReference, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSkillPackageReference) Or(d SkillPackageReference) SkillPackageReference {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSkillProposalMetadata returns new OptSkillProposalMetadata with value set to v.
func NewOptSkillProposalMetadata(v SkillProposalMetadata) OptSkillProposalMetadata {
	return OptSkillProposalMetadata{
		Value: v,
		Set:   true,
	}
}

// OptSkillProposalMetadata is optional SkillProposalMetadata.
type OptSkillProposalMetadata struct {
	Value SkillProposalMetadata
	Set   bool
}

// IsSet returns true if OptSkillProposalMetadata was set.
func (o OptSkillProposalMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSkillProposalMetadata) Reset() {
	var v SkillProposalMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSkillProposalMetadata) SetTo(v SkillProposalMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSkillProposalMetadata) Get() (v SkillProposalMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSkillProposalMetadata) Or(d SkillProposalMetadata) SkillProposalMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSourceReference returns new OptSourceReference with value set to v.
func NewOptSourceReference(v SourceReference) OptSourceReference {
	return OptSourceReference{
		Value: v,
		Set:   true,
	}
}

// OptSourceReference is optional SourceReference.
type OptSourceReference struct {
	Value SourceReference
	Set   bool
}

// IsSet returns true if OptSourceReference was set.
func (o OptSourceReference) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSourceReference) Reset() {
	var v SourceReference
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSourceReference) SetTo(v SourceReference) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSourceReference) Get() (v SourceReference, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSourceReference) Or(d SourceReference) SourceReference {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/ProposeSkillPackageRequest
type ProposeSkillPackageRequest struct {
	ArchiveBase64 string       `json:"archive_base64"`
	Reason        OptNilString `json:"reason"`
	ScopeID       string       `json:"scope_id"`
	// Exact managed Skill Revision replaced by this complete package Candidate.
	Target OptArtifactReference `json:"target"`
}

// GetArchiveBase64 returns the value of ArchiveBase64.
func (s *ProposeSkillPackageRequest) GetArchiveBase64() string {
	return s.ArchiveBase64
}

// GetReason returns the value of Reason.
func (s *ProposeSkillPackageRequest) GetReason() OptNilString {
	return s.Reason
}

// GetScopeID returns the value of ScopeID.
func (s *ProposeSkillPackageRequest) GetScopeID() string {
	return s.ScopeID
}

// GetTarget returns the value of Target.
func (s *ProposeSkillPackageRequest) GetTarget() OptArtifactReference {
	return s.Target
}

// SetArchiveBase64 sets the value of ArchiveBase64.
func (s *ProposeSkillPackageRequest) SetArchiveBase64(val string) {
	s.ArchiveBase64 = val
}

// SetReason sets the value of Reason.
func (s *ProposeSkillPackageRequest) SetReason(val OptNilString) {
	s.Reason = val
}

// SetScopeID sets the value of ScopeID.
func (s *ProposeSkillPackageRequest) SetScopeID(val string) {
	s.ScopeID = val
}

// SetTarget sets the value of Target.
func (s *ProposeSkillPackageRequest) SetTarget(val OptArtifactReference) {
	s.Target = val
}

// Ref: #/components/schemas/RecordSkillUsageRequest
type RecordSkillUsageRequest struct {
	EnvironmentFingerprint OptNilString                      `json:"environment_fingerprint"`
	Invoked                RecordSkillUsageRequestInvoked    `json:"invoked"`
	ObservationID          string                            `json:"observation_id"`
	Outcome                RecordSkillUsageRequestOutcome    `json:"outcome"`
	PackageDigest          string                            `json:"package_digest"`
	ScopeID                string                            `json:"scope_id"`
	Selected               bool                              `json:"selected"`
	SkillRef               ArtifactReference                 `json:"skill_ref"`
	TargetID               string                            `json:"target_id"`
	TaskSource             OptSourceReference                `json:"task_source"`
	Validation             RecordSkillUsageRequestValidation `json:"validation"`
}

// GetEnvironmentFingerprint returns the value of EnvironmentFingerprint.
func (s *RecordSkillUsageRequest) GetEnvironmentFingerprint() OptNilString {
	return s.EnvironmentFingerprint
}

// GetInvoked returns the value of Invoked.
func (s *RecordSkillUsageRequest) GetInvoked() RecordSkillUsageRequestInvoked {
	return s.Invoked
}

// GetObservationID returns the value of ObservationID.
func (s *RecordSkillUsageRequest) GetObservationID() string {
	return s.ObservationID
}

// GetOutcome returns the value of Outcome.
func (s *RecordSkillUsageRequest) GetOutcome() RecordSkillUsageRequestOutcome {
	return s.Outcome
}

// GetPackageDigest returns the value of PackageDigest.
func (s *RecordSkillUsageRequest) GetPackageDigest() string {
	return s.PackageDigest
}

// GetScopeID returns the value of ScopeID.
func (s *RecordSkillUsageRequest) GetScopeID() string {
	return s.ScopeID
}

// GetSelected returns the value of Selected.
func (s *RecordSkillUsageRequest) GetSelected() bool {
	return s.Selected
}

// GetSkillRef returns the value of SkillRef.
func (s *RecordSkillUsageRequest) GetSkillRef() ArtifactReference {
	return s.SkillRef
}

// GetTargetID returns the value of TargetID.
func (s *RecordSkillUsageRequest) GetTargetID() string {
	return s.TargetID
}

// GetTaskSource returns the value of TaskSource.
func (s *RecordSkillUsageRequest) GetTaskSource() OptSourceReference {
	return s.TaskSource
}

// GetValidation returns the value of Validation.
func (s *RecordSkillUsageRequest) GetValidation() RecordSkillUsageRequestValidation {
	return s.Validation
}

// SetEnvironmentFingerprint sets the value of EnvironmentFingerprint.
func (s *RecordSkillUsageRequest) SetEnvironmentFingerprint(val OptNilString) {
	s.EnvironmentFingerprint = val
}

// SetInvoked sets the value of Invoked.
func (s *RecordSkillUsageRequest) SetInvoked(val RecordSkillUsageRequestInvoked) {
	s.Invoked = val
}

// SetObservationID sets the value of ObservationID.
func (s *RecordSkillUsageRequest) SetObservationID(val string) {
	s.ObservationID = val
}

// SetOutcome sets the value of Outcome.
func (s *RecordSkillUsageRequest) SetOutcome(val RecordSkillUsageRequestOutcome) {
	s.Outcome = val
}

// SetPackageDigest sets the value of PackageDigest.
func (s *RecordSkillUsageRequest) SetPackageDigest(val string) {
	s.PackageDigest = val
}

// SetScopeID sets the value of ScopeID.
func (s *RecordSkillUsageRequest) SetScopeID(val string) {
	s.ScopeID = val
}

// SetSelected sets the value of Selected.
func (s *RecordSkillUsageRequest) SetSelected(val bool) {
	s.Selected = val
}

// SetSkillRef sets the value of SkillRef.
func (s *RecordSkillUsageRequest) SetSkillRef(val ArtifactReference) {
	s.SkillRef = val
}

// SetTargetID sets the value of TargetID.
func (s *RecordSkillUsageRequest) SetTargetID(val string) {
	s.TargetID = val
}

// SetTaskSource sets the value of TaskSource.
func (s *RecordSkillUsageRequest) SetTaskSource(val OptSourceReference) {
	s.TaskSource = val
}

// SetValidation sets the value of Validation.
func (s *RecordSkillUsageRequest) SetValidation(val RecordSkillUsageRequestValidation) {
	s.Validation = val
}

type RecordSkillUsageRequestInvoked string

const (
	RecordSkillUsageRequestInvokedTrue    RecordSkillUsageRequestInvoked = "true"
	RecordSkillUsageRequestInvokedFalse   RecordSkillUsageRequestInvoked = "false"
	RecordSkillUsageRequestInvokedUnknown RecordSkillUsageRequestInvoked = "unknown"
)

// AllValues returns all RecordSkillUsageRequestInvoked values.
func (RecordSkillUsageRequestInvoked) AllValues() []RecordSkillUsageRequestInvoked {
	return []RecordSkillUsageRequestInvoked{
		RecordSkillUsageRequestInvokedTrue,
		RecordSkillUsageRequestInvokedFalse,
		RecordSkillUsageRequestInvokedUnknown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RecordSkillUsageRequestInvoked) MarshalText() ([]byte, error) {
	switch s {
	case RecordSkillUsageRequestInvokedTrue:
		return []byte(s), nil
	case RecordSkillUsageRequestInvokedFalse:
		return []byte(s), nil
	case RecordSkillUsageRequestInvokedUnknown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RecordSkillUsageRequestInvoked) UnmarshalText(data []byte) error {
	switch RecordSkillUsageRequestInvoked(data) {
	case RecordSkillUsageRequestInvokedTrue:
		*s = RecordSkillUsageRequestInvokedTrue
		return nil
	case RecordSkillUsageRequestInvokedFalse:
		*s = RecordSkillUsageRequestInvokedFalse
		return nil
	case RecordSkillUsageRequestInvokedUnknown:
		*s = RecordSkillUsageRequestInvokedUnknown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type RecordSkillUsageRequestOutcome string

const (
	RecordSkillUsageRequestOutcomeSuccess RecordSkillUsageRequestOutcome = "success"
	RecordSkillUsageRequestOutcomeFailure RecordSkillUsageRequestOutcome = "failure"
	RecordSkillUsageRequestOutcomeUnknown RecordSkillUsageRequestOutcome = "unknown"
)

// AllValues returns all RecordSkillUsageRequestOutcome values.
func (RecordSkillUsageRequestOutcome) AllValues() []RecordSkillUsageRequestOutcome {
	return []RecordSkillUsageRequestOutcome{
		RecordSkillUsageRequestOutcomeSuccess,
		RecordSkillUsageRequestOutcomeFailure,
		RecordSkillUsageRequestOutcomeUnknown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RecordSkillUsageRequestOutcome) MarshalText() ([]byte, error) {
	switch s {
	case RecordSkillUsageRequestOutcomeSuccess:
		return []byte(s), nil
	case RecordSkillUsageRequestOutcomeFailure:
		return []byte(s), nil
	case RecordSkillUsageRequestOutcomeUnknown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RecordSkillUsageRequestOutcome) UnmarshalText(data []byte) error {
	switch RecordSkillUsageRequestOutcome(data) {
	case RecordSkillUsageRequestOutcomeSuccess:
		*s = RecordSkillUsageRequestOutcomeSuccess
		return nil
	case RecordSkillUsageRequestOutcomeFailure:
		*s = RecordSkillUsageRequestOutcomeFailure
		return nil
	case RecordSkillUsageRequestOutcomeUnknown:
		*s = RecordSkillUsageRequestOutcomeUnknown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type RecordSkillUsageRequestValidation string

const (
	RecordSkillUsageRequestValidationPassed  RecordSkillUsageRequestValidation = "passed"
	RecordSkillUsageRequestValidationFailed  RecordSkillUsageRequestValidation = "failed"
	RecordSkillUsageRequestValidationUnknown RecordSkillUsageRequestValidation = "unknown"
)

// AllValues returns all RecordSkillUsageRequestValidation values.
func (RecordSkillUsageRequestValidation) AllValues() []RecordSkillUsageRequestValidation {
	return []RecordSkillUsageRequestValidation{
		RecordSkillUsageRequestValidationPassed,
		RecordSkillUsageRequestValidationFailed,
		RecordSkillUsageRequestValidationUnknown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RecordSkillUsageRequestValidation) MarshalText() ([]byte, error) {
	switch s {
	case RecordSkillUsageRequestValidationPassed:
		return []byte(s), nil
	case RecordSkillUsageRequestValidationFailed:
		return []byte(s), nil
	case RecordSkillUsageRequestValidationUnknown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RecordSkillUsageRequestValidation) UnmarshalText(data []byte) error {
	switch RecordSkillUsageRequestValidation(data) {
	case RecordSkillUsageRequestValidationPassed:
		*s = RecordSkillUsageRequestValidationPassed
		return nil
	case RecordSkillUsageRequestValidationFailed:
		*s = RecordSkillUsageRequestValidationFailed
		return nil
	case RecordSkillUsageRequestValidationUnknown:
		*s = RecordSkillUsageRequestValidationUnknown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/SkillPackageDownload
type SkillPackageDownload struct {
	ArchiveBase64 string                `json:"archive_base64"`
	Package       SkillPackageReference `json:"package"`
}

// GetArchiveBase64 returns the value of ArchiveBase64.
func (s *SkillPackageDownload) GetArchiveBase64() string {
	return s.ArchiveBase64
}

// GetPackage returns the value of Package.
func (s *SkillPackageDownload) GetPackage() SkillPackageReference {
	return s.Package
}

// SetArchiveBase64 sets the value of ArchiveBase64.
func (s *SkillPackageDownload) SetArchiveBase64(val string) {
	s.ArchiveBase64 = val
}

// SetPackage sets the value of Package.
func (s *SkillPackageDownload) SetPackage(val SkillPackageReference) {
	s.Package = val
}

func (*SkillPackageDownload) downloadSkillPackageRes() {}

// Ref: #/components/schemas/SkillPackageFile
type SkillPackageFile struct {
	Digest     string `json:"digest"`
	Executable bool   `json:"executable"`
	MediaType  string `json:"media_type"`
	Path       string `json:"path"`
	Size       int    `json:"size"`
}

// GetDigest returns the value of Digest.
func (s *SkillPackageFile) GetDigest() string {
	return s.Digest
}

// GetExecutable returns the value of Executable.
func (s *SkillPackageFile) GetExecutable() bool {
	return s.Executable
}

// GetMediaType returns the value of MediaType.
func (s *SkillPackageFile) GetMediaType() string {
	return s.MediaType
}

// GetPath returns the value of Path.
func (s *SkillPackageFile) GetPath() string {
	return s.Path
}

// GetSize returns the value of Size.
func (s *SkillPackageFile) GetSize() int {
	return s.Size
}

// SetDigest sets the value of Digest.
func (s *SkillPackageFile) SetDigest(val string) {
	s.Digest = val
}

// SetExecutable sets the value of Executable.
func (s *SkillPackageFile) SetExecutable(val bool) {
	s.Executable = val
}

// SetMediaType sets the value of MediaType.
func (s *SkillPackageFile) SetMediaType(val string) {
	s.MediaType = val
}

// SetPath sets the value of Path.
func (s *SkillPackageFile) SetPath(val string) {
	s.Path = val
}

// SetSize sets the value of Size.
func (s *SkillPackageFile) SetSize(val int) {
	s.Size = val
}

// Ref: #/components/schemas/SkillPackageManifest
type SkillPackageManifest struct {
	AllowedTools  OptNilString                 `json:"allowed_tools"`
	Compatibility OptNilString                 `json:"compatibility"`
	Description   string                       `json:"description"`
	Files         []SkillPackageFile           `json:"files"`
	License       OptNilString                 `json:"license"`
	Metadata      SkillPackageManifestMetadata `json:"metadata"`
	Name          string                       `json:"name"`
	Package       SkillPackageReference        `json:"package"`
}

// GetAllowedTools returns the value of AllowedTools.
func (s *SkillPackageManifest) GetAllowedTools() OptNilString {
	return s.AllowedTools
}

// GetCompatibility returns the value of Compatibility.
func (s *SkillPackageManifest) GetCompatibility() OptNilString {
	return s.Compatibility
}

// GetDescription returns the value of Description.
func (s *SkillPackageManifest) GetDescription() string {
	return s.Description
}

// GetFiles returns the value of Files.
func (s *SkillPackageManifest) GetFiles() []SkillPackageFile {
	return s.Files
}

// GetLicense returns the value of License.
func (s *SkillPackageManifest) GetLicense() OptNilString {
	return s.License
}

// GetMetadata returns the value of Metadata.
func (s *SkillPackageManifest) GetMetadata() SkillPackageManifestMetadata {
	return s.Metadata
}

// GetName returns the value of Name.
func (s *SkillPackageManifest) GetName() string {
	return s.Name
}

// GetPackage returns the value of Package.
func (s *SkillPackageManifest) GetPackage() SkillPackageReference {
	return s.Package
}

// SetAllowedTools sets the value of AllowedTools.
func (s *SkillPackageManifest) SetAllowedTools(val OptNilString) {
	s.AllowedTools = val
}

// SetCompatibility sets the value of Compatibility.
func (s *SkillPackageManifest) SetCompatibility(val OptNilString) {
	s.Compatibility = val
}

// SetDescription sets the value of Description.
func (s *SkillPackageManifest) SetDescription(val string) {
	s.Description = val
}

// SetFiles sets the value of Files.
func (s *SkillPackageManifest) SetFiles(val []SkillPackageFile) {
	s.Files = val
}

// SetLicense sets the value of License.
func (s *SkillPackageManifest) SetLicense(val OptNilString) {
	s.License = val
}

// SetMetadata sets the value of Metadata.
func (s *SkillPackageManifest) SetMetadata(val SkillPackageManifestMetadata) {
	s.Metadata = val
}

// SetName sets the value of Name.
func (s *SkillPackageManifest) SetName(val string) {
	s.Name = val
}

// SetPackage sets the value of Package.
func (s *SkillPackageManifest) SetPackage(val SkillPackageReference) {
	s.Package = val
}

func (*SkillPackageManifest) getSkillPackageManifestRes() {}

type SkillPackageManifestMetadata map[string]string

func (s *SkillPackageManifestMetadata) init() SkillPackageManifestMetadata {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/SkillPackageReference
type SkillPackageReference struct {
	ArchiveDigest    string `json:"archive_digest"`
	ArchiveSize      int    `json:"archive_size"`
	FileCount        int    `json:"file_count"`
	TreeDigest       string `json:"tree_digest"`
	UncompressedSize int    `json:"uncompressed_size"`
}

// GetArchiveDigest returns the value of ArchiveDigest.
func (s *SkillPackageReference) GetArchiveDigest() string {
	return s.ArchiveDigest
}

// GetArchiveSize returns the value of ArchiveSize.
func (s *SkillPackageReference) GetArchiveSize() int {
	return s.ArchiveSize
}

// GetFileCount returns the value of FileCount.
func (s *SkillPackageReference) GetFileCount() int {
	return s.FileCount
}

// GetTreeDigest returns the value of TreeDigest.
func (s *SkillPackageReference) GetTreeDigest() string {
	return s.TreeDigest
}

// GetUncompressedSize returns the value of UncompressedSize.
func (s *SkillPackageReference) GetUncompressedSize() int {
	return s.UncompressedSize
}

// SetArchiveDigest sets the value of ArchiveDigest.
func (s *SkillPackageReference) SetArchiveDigest(val string) {
	s.ArchiveDigest = val
}

// SetArchiveSize sets the value of ArchiveSize.
func (s *SkillPackageReference) SetArchiveSize(val int) {
	s.ArchiveSize = val
}

// SetFileCount sets the value of FileCount.
func (s *SkillPackageReference) SetFileCount(val int) {
	s.FileCount = val
}

// SetTreeDigest sets the value of TreeDigest.
func (s *SkillPackageReference) SetTreeDigest(val string) {
	s.TreeDigest = val
}

// SetUncompressedSize sets the value of UncompressedSize.
func (s *SkillPackageReference) SetUncompressedSize(val int) {
	s.UncompressedSize = val
}

// Ref: #/components/schemas/SkillProposal
type SkillProposal struct {
	AllowedTools  OptNilString             `json:"allowed_tools"`
	Compatibility OptNilString             `json:"compatibility"`
	Description   string                   `json:"description"`
	Instructions  string                   `json:"instructions"`
	License       OptNilString             `json:"license"`
	Metadata      OptSkillProposalMetadata `json:"metadata"`
	Name          string                   `json:"name"`
	Package       OptSkillPackageReference `json:"package"`
	Validation    []SkillValidationItem    `json:"validation"`
}

// GetAllowedTools returns the value of AllowedTools.
func (s *SkillProposal) GetAllowedTools() OptNilString {
	return s.AllowedTools
}

// GetCompatibility returns the value of Compatibility.
func (s *SkillProposal) GetCompatibility() OptNilString {
	return s.Compatibility
}

// GetDescription returns the value of Description.
func (s *SkillProposal) GetDescription() string {
	return s.Description
}

// GetInstructions returns the value of Instructions.
func (s *SkillProposal) GetInstructions() string {
	return s.Instructions
}

// GetLicense returns the value of License.
func (s *SkillProposal) GetLicense() OptNilString {
	return s.License
}

// GetMetadata returns the value of Metadata.
func (s *SkillProposal) GetMetadata() OptSkillProposalMetadata {
	return s.Metadata
}

// GetName returns the value of Name.
func (s *SkillProposal) GetName() string {
	return s.Name
}

// GetPackage returns the value of Package.
func (s *SkillProposal) GetPackage() OptSkillPackageReference {
	return s.Package
}

// GetValidation returns the value of Validation.
func (s *SkillProposal) GetValidation() []SkillValidationItem {
	return s.Validation
}

// SetAllowedTools sets the value of AllowedTools.
func (s *SkillProposal) SetAllowedTools(val OptNilString) {
	s.AllowedTools = val
}

// SetCompatibility sets the value of Compatibility.
func (s *SkillProposal) SetCompatibility(val OptNilString) {
	s.Compatibility = val
}

// SetDescription sets the value of Description.
func (s *SkillProposal) SetDescription(val string) {
	s.Description = val
}

// SetInstructions sets the value of Instructions.
func (s *SkillProposal) SetInstructions(val string) {
	s.Instructions = val
}

// SetLicense sets the value of License.
func (s *SkillProposal) SetLicense(val OptNilString) {
	s.License = val
}

// SetMetadata sets the value of Metadata.
func (s *SkillProposal) SetMetadata(val OptSkillProposalMetadata) {
	s.Metadata = val
}

// SetName sets the value of Name.
func (s *SkillProposal) SetName(val string) {
	s.Name = val
}

// SetPackage sets the value of Package.
func (s *SkillProposal) SetPackage(val OptSkillPackageReference) {
	s.Package = val
}

// SetValidation sets the value of Validation.
func (s *SkillProposal) SetValidation(val []SkillValidationItem) {
	s.Validation = val
}

type SkillProposalMetadata map[string]string

func (s *SkillProposalMetadata) init() SkillProposalMetadata {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

type SkillValidationItem string

// Ref: #/components/schemas/SourceReference
type SourceReference struct {
	// Stable Source type.
	Name     string `json:"name"`
	SourceID string `json:"source_id"`
}

// GetName returns the value of Name.
func (s *SourceReference) GetName() string {
	return s.Name
}

// GetSourceID returns the value of SourceID.
func (s *SourceReference) GetSourceID() string {
	return s.SourceID
}

// SetName sets the value of Name.
func (s *SourceReference) SetName(val string) {
	s.Name = val
}

// SetSourceID sets the value of SourceID.
func (s *SourceReference) SetSourceID(val string) {
	s.SourceID = val
}

// UnauthorizedHeaders wraps ErrorResponse with response headers.
type UnauthorizedHeaders struct {
	WWWAuthenticate        OptString
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetWWWAuthenticate returns the value of WWWAuthenticate.
func (s *UnauthorizedHeaders) GetWWWAuthenticate() OptString {
	return s.WWWAuthenticate
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *UnauthorizedHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *UnauthorizedHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetWWWAuthenticate sets the value of WWWAuthenticate.
func (s *UnauthorizedHeaders) SetWWWAuthenticate(val OptString) {
	s.WWWAuthenticate = val
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *UnauthorizedHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *UnauthorizedHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*UnauthorizedHeaders) downloadSkillPackageRes()    {}
func (*UnauthorizedHeaders) getSkillPackageManifestRes() {}
func (*UnauthorizedHeaders) proposeSkillPackageRes()     {}
func (*UnauthorizedHeaders) recordSkillUsageRes()        {}

// UnavailableHeaders wraps ErrorResponse with response headers.
type UnavailableHeaders struct {
	XPowerContextRequestID OptString
	Response               ErrorResponse
}

// GetXPowerContextRequestID returns the value of XPowerContextRequestID.
func (s *UnavailableHeaders) GetXPowerContextRequestID() OptString {
	return s.XPowerContextRequestID
}

// GetResponse returns the value of Response.
func (s *UnavailableHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetXPowerContextRequestID sets the value of XPowerContextRequestID.
func (s *UnavailableHeaders) SetXPowerContextRequestID(val OptString) {
	s.XPowerContextRequestID = val
}

// SetResponse sets the value of Response.
func (s *UnavailableHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*UnavailableHeaders) downloadSkillPackageRes()    {}
func (*UnavailableHeaders) getSkillPackageManifestRes() {}
func (*UnavailableHeaders) proposeSkillPackageRes()     {}
func (*UnavailableHeaders) recordSkillUsageRes()        {}
